currencies = [
    {'full name': 'US Dollar', 'abbreviation': 'USD'},
    {'full name': 'Euro', 'abbreviation': 'EUR'},
    {'full name': 'Japanese Yen', 'abbreviation': 'JPY'},
    {'full name': 'British Pound Sterling', 'abbreviation': 'GBP'},
    {'full name': 'Australian Dollar', 'abbreviation': 'AUD'},
    {'full name': 'Canadian Dollar', 'abbreviation': 'CAD'},
    {'full name': 'Swiss Franc', 'abbreviation': 'CHF'},
    {'full name': 'Chinese Yuan', 'abbreviation': 'CNY'},
    {'full name': 'Swedish Krona', 'abbreviation': 'SEK'},
    {'full name': 'New Zealand Dollar', 'abbreviation': 'NZD'},
    {'full name': 'Arab Emirates Dirham', 'abbreviation': 'AED'},
    {'full name': 'Afghan Afghani', 'abbreviation': 'AFN'},
    {'full name': 'Albania Lek', 'abbreviation': 'ALL'},
    {'full name': 'Armenian Dram', 'abbreviation': 'AMD'},
    {'full name': 'Netherlands Antillean Guilder', 'abbreviation': 'ANG'},
    {'full name': 'Angolan Kwanza', 'abbreviation': 'AOA'},
    {'full name': 'Argentine Peso', 'abbreviation': 'ARS'},
    {'full name': 'Aruban Florin', 'abbreviation': 'AWG'},
    {'full name': 'Azerbaijani Manat', 'abbreviation': 'AZN'},
    {'full name': 'Bosnia-Herzegovina Convertible Mark', 'abbreviation': 'BAM'},
    {'full name': 'Barbadian Dollar', 'abbreviation': 'BBD'},
    {'full name': 'Bangladeshi Taka', 'abbreviation': 'BDT'},
    {'full name': 'Bulgarian Lev', 'abbreviation': 'BGN'},
    {'full name': 'Bahraini Dinar', 'abbreviation': 'BHD'},
    {'full name': 'Burundian Franc', 'abbreviation': 'BIF'},
    {'full name': 'Bermudan Dollar', 'abbreviation': 'BMD'},
    {'full name': 'Brunei Dollar', 'abbreviation': 'BND'},
    {'full name': 'Bolivian Boliviano', 'abbreviation': 'BOB'},
    {'full name': 'Brazilian Real', 'abbreviation': 'BRL'},
    {'full name': 'Bahamian Dollar', 'abbreviation': 'BSD'},
    {'full name': 'Bhutanese Ngultrum', 'abbreviation': 'BTN'},
    {'full name': 'Botswanan Pula', 'abbreviation': 'BWP'},
    {'full name': 'Belarusian Ruble', 'abbreviation': 'BYR'},
    {'full name': 'Belize Dollar', 'abbreviation': 'BZD'},
    {'full name': 'Congolese Franc', 'abbreviation': 'CDF'},
    {'full name': 'Chilean Unit of Account', 'abbreviation': 'CLF'},
    {'full name': 'Chilean Peso', 'abbreviation': 'CLP'},
    {'full name': 'Colombian Peso', 'abbreviation': 'COP'},
    {'full name': 'Costa Rican Colón', 'abbreviation': 'CRC'},
    {'full name': 'Cuban Convertible Peso', 'abbreviation': 'CUC'},
    {'full name': 'Cuban Peso', 'abbreviation': 'CUP'},
    {'full name': 'Cape Verdean Escudo', 'abbreviation': 'CVE'},
    {'full name': 'Czech Republic Koruna', 'abbreviation': 'CZK'},
    {'full name': 'Djiboutian Franc', 'abbreviation': 'DJF'},
    {'full name': 'Danish Krone', 'abbreviation': 'DKK'},
    {'full name': 'Dominican Peso', 'abbreviation': 'DOP'},
    {'full name': 'Algerian Dinar', 'abbreviation': 'DZD'},
    {'full name': 'Egyptian Pound', 'abbreviation': 'EGP'},
    {'full name': 'Eritrean Nakfa', 'abbreviation': 'ERN'},
    {'full name': 'Ethiopian Birr', 'abbreviation': 'ETB'},
    {'full name': 'Fijian Dollar', 'abbreviation': 'FJD'},
    {'full name': 'Falkland Islands Pound', 'abbreviation': 'FKP'},
    {'full name': 'Georgian Lari', 'abbreviation': 'GEL'},
    {'full name': 'Ghanaian Cedi', 'abbreviation': 'GHS'},
    {'full name': 'Gibraltar Pound', 'abbreviation': 'GIP'},
    {'full name': 'Gambian Dalasi', 'abbreviation': 'GMD'},
    {'full name': 'Guinean Franc', 'abbreviation': 'GNF'},
    {'full name': 'Guatemalan Quetzal', 'abbreviation': 'GTQ'},
    {'full name': 'Guyanaese Dollar', 'abbreviation': 'GYD'},
    {'full name': 'Hong Kong Dollar', 'abbreviation': 'HKD'},
    {'full name': 'Honduran Lempira', 'abbreviation': 'HNL'},
    {'full name': 'Croatian Kuna', 'abbreviation': 'HRK'},
    {'full name': 'Haitian Gourde', 'abbreviation': 'HTG'},
    {'full name': 'Hungarian Forint', 'abbreviation': 'HUF'},
    {'full name': 'Indonesian Rupiah', 'abbreviation': 'IDR'},
    {'full name': 'Israeli New Sheqel', 'abbreviation': 'ILS'},
    {'full name': 'Manx pound', 'abbreviation': 'IMP'},
    {'full name': 'Indian Rupee', 'abbreviation': 'INR'},
    {'full name': 'Iraqi Dinar', 'abbreviation': 'IQD'},
    {'full name': 'Iranian Rial', 'abbreviation': 'IRR'},
    {'full name': 'Icelandic Króna', 'abbreviation': 'ISK'},
    {'full name': 'Jersey Pound', 'abbreviation': 'JEP'},
    {'full name': 'Jamaican Dollar', 'abbreviation': 'JMD'},
    {'full name': 'Jordanian Dinar', 'abbreviation': 'JOD'},
    {'full name': 'Kenyan Shilling', 'abbreviation': 'KES'},
    {'full name': 'Kyrgystani Som', 'abbreviation': 'KGS'},
    {'full name': 'Cambodian Riel', 'abbreviation': 'KHR'},
    {'full name': 'Comorian Franc', 'abbreviation': 'KMF'},
    {'full name': 'North Korean Won', 'abbreviation': 'KPW'},
    {'full name': 'South Korean Won', 'abbreviation': 'KRW'},
    {'full name': 'Kuwaiti Dinar', 'abbreviation': 'KWD'},
    {'full name': 'Cayman Islands Dollar', 'abbreviation': 'KYD'},
    {'full name': 'Kazakhstani Tenge', 'abbreviation': 'KZT'},
    {'full name': 'Laotian Kip', 'abbreviation': 'LAK'},
    {'full name': 'Lebanese Pound', 'abbreviation': 'LBP'},
    {'full name': 'Sri Lankan Rupee', 'abbreviation': 'LKR'},
    {'full name': 'Liberian Dollar', 'abbreviation': 'LRD'},
    {'full name': 'Lesotho Loti', 'abbreviation': 'LSL'},
    {'full name': 'Lithuanian Litas', 'abbreviation': 'LTL'},
    {'full name': 'Latvian Lats', 'abbreviation': 'LVL'},
    {'full name': 'Libyan Dinar', 'abbreviation': 'LYD'},
    {'full name': 'Moroccan Dirham', 'abbreviation': 'MAD'},
    {'full name': 'Moldovan Leu', 'abbreviation': 'MDL'},
    {'full name': 'Malagasy Ariary', 'abbreviation': 'MGA'},
    {'full name': 'Macedonian Denar', 'abbreviation': 'MKD'},
    {'full name': 'Myanma Kyat', 'abbreviation': 'MMK'},
    {'full name': 'Mongolian Tugrik', 'abbreviation': 'MNT'},
    {'full name': 'Macanese Pataca', 'abbreviation': 'MOP'},
    {'full name': 'Mauritanian Ouguiya', 'abbreviation': 'MRO'},
    {'full name': 'Mauritian Rupee', 'abbreviation': 'MUR'},
    {'full name': 'Maldivian Rufiyaa', 'abbreviation': 'MVR'},
    {'full name': 'Malawian Kwacha', 'abbreviation': 'MWK'},
    {'full name': 'Mexican Peso', 'abbreviation': 'MXN'},
    {'full name': 'Malaysian Ringgit', 'abbreviation': 'MYR'},
    {'full name': 'Mozambican Metical', 'abbreviation': 'MZN'},
    {'full name': 'Namibian Dollar', 'abbreviation': 'NAD'},
    {'full name': 'Nigerian Naira', 'abbreviation': 'NGN'},
    {'full name': 'Nicaraguan Córdoba', 'abbreviation': 'NIO'},
    {'full name': 'Norwegian Krone', 'abbreviation': 'NOK'},
    {'full name': 'Nepalese Rupee', 'abbreviation': 'NPR'},
    {'full name': 'Omani Rial', 'abbreviation': 'OMR'},
    {'full name': 'Panamanian Balboa', 'abbreviation': 'PAB'},
    {'full name': 'Peruvian Nuevo Sol', 'abbreviation': 'PEN'},
    {'full name': 'Papua New Guinean Kina', 'abbreviation': 'PGK'},
    {'full name': 'Philippine Peso', 'abbreviation': 'PHP'},
    {'full name': 'Pakistani Rupee', 'abbreviation': 'PKR'},
    {'full name': 'Polish Zloty', 'abbreviation': 'PLN'},
    {'full name': 'Paraguayan Guarani', 'abbreviation': 'PYG'},
    {'full name': 'Qatari Rial', 'abbreviation': 'QAR'},
    {'full name': 'Romanian Leu', 'abbreviation': 'RON'},
    {'full name': 'Serbian Dinar', 'abbreviation': 'RSD'},
    {'full name': 'Russian Ruble', 'abbreviation': 'RUB'},
    {'full name': 'Rwandan Franc', 'abbreviation': 'RWF'},
    {'full name': 'Saudi Riyal', 'abbreviation': 'SAR'},
    {'full name': 'Solomon Islands Dollar', 'abbreviation': 'SBD'},
    {'full name': 'Seychellois Rupee', 'abbreviation': 'SCR'},
    {'full name': 'Sudanese Pound', 'abbreviation': 'SDG'},
    {'full name': 'Singapore Dollar', 'abbreviation': 'SGD'},
    {'full name': 'Saint Helena Pound', 'abbreviation': 'SHP'},
    {'full name': 'Sierra Leonean Leone', 'abbreviation': 'SLL'},
    {'full name': 'Somali Shilling', 'abbreviation': 'SOS'},
    {'full name': 'Surinamese Dollar', 'abbreviation': 'SRD'},
    {'full name': 'São Tomé and Príncipe Dobra', 'abbreviation': 'STD'},
    {'full name': 'Salvadoran Colón', 'abbreviation': 'SVC'},
    {'full name': 'Syrian Pound', 'abbreviation': 'SYP'},
    {'full name': 'Swazi Lilangeni', 'abbreviation': 'SZL'},
    {'full name': 'Thai Baht', 'abbreviation': 'THB'},
    {'full name': 'Tajikistani Somoni', 'abbreviation': 'TJS'},
    {'full name': 'Turkmenistani Manat', 'abbreviation': 'TMT'},
    {'full name': 'Tunisian Dinar', 'abbreviation': 'TND'},
    {'full name': 'Tongan Paʻanga', 'abbreviation': 'TOP'},
    {'full name': 'Turkish Lira', 'abbreviation': 'TRY'},
    {'full name': 'Trinidad and Tobago Dollar', 'abbreviation': 'TTD'},
    {'full name': 'New Taiwan Dollar', 'abbreviation': 'TWD'},
    {'full name': 'Tanzanian Shilling', 'abbreviation': 'TZS'},
    {'full name': 'Ukrainian Hryvnia', 'abbreviation': 'UAH'},
    {'full name': 'Ugandan Shilling', 'abbreviation': 'UGX'},
    {'full name': 'Uruguayan Peso', 'abbreviation': 'UYU'},
    {'full name': 'Uzbekistan Som', 'abbreviation': 'UZS'},
    {'full name': 'Venezuelan Bolívar Fuerte', 'abbreviation': 'VEF'},
    {'full name': 'Vietnamese Dong', 'abbreviation': 'VND'},
    {'full name': 'Vanuatu Vatu', 'abbreviation': 'VUV'},
    {'full name': 'Samoan Tala', 'abbreviation': 'WST'},
    {'full name': 'CFA Franc BEAC', 'abbreviation': 'XAF'},
    {'full name': 'East Caribbean Dollar', 'abbreviation': 'XCD'},
    {'full name': 'CFA Franc BCEAO', 'abbreviation': 'XOF'},
    {'full name': 'CFP Franc', 'abbreviation': 'XPF'},
    {'full name': 'Yemeni Rial', 'abbreviation': 'YER'},
    {'full name': 'South African Rand', 'abbreviation': 'ZAR'},
    {'full name': 'Zambian Kwacha', 'abbreviation': 'ZMW'},
    {'full name': 'Zimbabwean Dollar', 'abbreviation': 'ZWL'}
]
crypto_currencies = [
    {'full name': 'Bitcoin', 'abbreviation': 'BTC'},
    {'full name': 'Ethereum', 'abbreviation': 'ETH'},
    {'full name': 'Cardano', 'abbreviation': 'ADA'},
    {'full name': 'Binance Coin', 'abbreviation': 'BNB'},
    {'full name': 'TETHER', 'abbreviation': 'USDT'},
    {'full name': 'Solona', 'abbreviation': 'SOL'},
    {'full name': 'Xrp', 'abbreviation': 'XRP'},
    {'full name': 'Dogecoin', 'abbreviation': 'DOGE'},
    {'full name': 'Polkadot', 'abbreviation': 'DOT'},
    {'full name': 'USD Coin', 'abbreviation': 'USDC'},
    {'full name': 'Terra', 'abbreviation': 'LUNA'},
    {'full name': 'Uniswap', 'abbreviation': 'UNI'},
    {'full name': 'Chainlink', 'abbreviation': 'LINK'},
    {'full name': 'Binance USD', 'abbreviation': 'BUSD'},
    {'full name': 'Bitcoin Cash', 'abbreviation': 'BCH'},
    {'full name': 'Litecoin', 'abbreviation': 'LTC'},
    {'full name': 'Algorand', 'abbreviation': 'ALGO'},
    {'full name': 'Avalanche', 'abbreviation': 'AVAX'},
    {'full name': 'Internet Computer', 'abbreviation': 'ICP'},
    {'full name': 'Wrapped Bitcoin', 'abbreviation': 'WBTC'},
    {'full name': 'Polygon', 'abbreviation': 'MATIC'},
    {'full name': 'FTX Token', 'abbreviation': 'FTT'},
    {'full name': 'Filecoin', 'abbreviation': 'FIL'},
    {'full name': 'Stellar', 'abbreviation': 'XLM'},
    {'full name': 'VeChain', 'abbreviation': 'VET'},
    {'full name': 'Ethereum Classic', 'abbreviation': 'ETC'},
    {'full name': 'Theta', 'abbreviation': 'THETA'},
    {'full name': 'Dai', 'abbreviation': 'DAI'},
    {'full name': 'Tron', 'abbreviation': 'TRX'},
    {'full name': 'Cosmos', 'abbreviation': 'ATOM'},
    {'full name': 'Tezos', 'abbreviation': 'XTZ'},
    {'full name': 'Monero', 'abbreviation': 'XMR'},
    {'full name': 'IOTA', 'abbreviation': 'MIOTA'},
    {'full name': 'EOS', 'abbreviation': 'EOS'},
    {'full name': 'ECash', 'abbreviation': 'XEC'},
    {'full name': 'Crypto.com Coin', 'abbreviation': 'CRO'},
    {'full name': 'PancakeSwap', 'abbreviation': 'CAKE'},
    {'full name': 'Elrond', 'abbreviation': 'EGLD'},
    {'full name': 'Aave', 'abbreviation': 'AAVE'},
    {'full name': 'NEAR Protocol', 'abbreviation': 'NEAR'},
    {'full name': 'Axie Infinity', 'abbreviation': 'AXS'},
    {'full name': 'Fantom', 'abbreviation': 'FTM'},
    {'full name': 'The Graph', 'abbreviation': 'GRT'},
    {'full name': 'Quant', 'abbreviation': 'QNT'},
    {'full name': 'Bitcoin BEP2', 'abbreviation': 'BTCB'},
    {'full name': 'Neo', 'abbreviation': 'NEO'},
    {'full name': 'Klaytn', 'abbreviation': 'KLAY'},
    {'full name': 'Kusama', 'abbreviation': 'KSM'},
    {'full name': 'Waves', 'abbreviation': 'WAVES'},
    {'full name': 'Hedera Hashgraph', 'abbreviation': 'HBAR'},
    {'full name': 'Bitcoin SV', 'abbreviation': 'BSV'},
    {'full name': 'UNUS SED LEO', 'abbreviation': 'LEO'},
    {'full name': 'Maker', 'abbreviation': 'MKR'},
    {'full name': 'SHIBA INU', 'abbreviation': 'SHIB'},
    {'full name': 'BitTorrent', 'abbreviation': 'BTT'},
    {'full name': 'TerraUSD', 'abbreviation': 'UST'},
    {'full name': 'Huobi Token', 'abbreviation': 'HT'},
    {'full name': 'Amp', 'abbreviation': 'AMP'},
    {'full name': 'Compound', 'abbreviation': 'COMP'},
    {'full name': 'Arweave', 'abbreviation': 'AR'},
    {'full name': 'Dash', 'abbreviation': 'DASH'},
    {'full name': 'Revain', 'abbreviation': 'REV'},
    {'full name': 'Chiliz', 'abbreviation': 'CHZ'},
    {'full name': 'Decred', 'abbreviation': 'DCR'},
    {'full name': 'THORChain', 'abbreviation': 'RUNE'},
    {'full name': 'Helium', 'abbreviation': 'HNT'},
    {'full name': 'Harmony', 'abbreviation': 'ONE'},
    {'full name': 'Stacks', 'abbreviation': 'STX'},
    {'full name': 'Holo', 'abbreviation': 'HOT'},
    {'full name': 'Zcash', 'abbreviation': 'ZEC'},
    {'full name': 'Theta Fuel', 'abbreviation': 'TFUEL'},
    {'full name': 'NEM', 'abbreviation': 'XEM'},
    {'full name': 'Celo', 'abbreviation': 'CELO'},
    {'full name': 'XinFin', 'abbreviation': 'XDC'},
    {'full name': 'Decentraland', 'abbreviation': 'MANA'},
    {'full name': 'Enjin Coin', 'abbreviation': 'ENJ'},
    {'full name': 'TrueUSD', 'abbreviation': 'TUSD'},
    {'full name': 'IOST', 'abbreviation': 'IOST'},
    {'full name': 'Celsius', 'abbreviation': 'CEL'},
    {'full name': 'Sushiswap', 'abbreviation': 'SUSHI'},
    {'full name': 'Zilliqa', 'abbreviation': 'ZIL'},
    {'full name': 'Qtum', 'abbreviation': 'QTUM'},
    {'full name': 'Synthetix', 'abbreviation': 'SNX'},
    {'full name': 'ICON', 'abbreviation': 'ICX'},
    {'full name': 'Yearn.finance', 'abbreviation': 'YFI'},
    {'full name': 'Mdex', 'abbreviation': 'MDX'},
    {'full name': 'Mina', 'abbreviation': 'MINA'},
    {'full name': 'OMG Network', 'abbreviation': 'OMG'},
    {'full name': 'Bitcoin Gold', 'abbreviation': 'BTG'},
    {'full name': 'Flow', 'abbreviation': 'FLOW'},
    {'full name': 'Basic Attention Token', 'abbreviation': 'BAT'},
    {'full name': 'Ravencoin', 'abbreviation': 'RVN'},
    {'full name': 'OKB', 'abbreviation': 'OKB'},
    {'full name': 'Telcoin', 'abbreviation': 'TEL'},
    {'full name': 'Audius', 'abbreviation': 'AUDIO'},
    {'full name': 'Curve DAO Token', 'abbreviation': 'PERP'},
    {'full name': 'Horizen', 'abbreviation': 'ZEN'},
    {'full name': 'Bancor', 'abbreviation': 'BNT'},
    {'full name': 'Siacoin', 'abbreviation': 'SC'},
]
