# © Designed and Developed by Mehmet Güdük.
# © Licensed with GPL-3.0 License, Author is Mehmet Güdük.


# The visual and design part of the application is here.


from PyQt5 import QtCore, QtGui, QtWidgets

import currencies


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(500, 400))
        MainWindow.setMaximumSize(QtCore.QSize(500, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/images/logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 461, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupbox_HAVE = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupbox_HAVE.setObjectName("groupbox_HAVE")
        self.label_HAVE_title_currencies = QtWidgets.QLabel(self.groupbox_HAVE)
        self.label_HAVE_title_currencies.setGeometry(QtCore.QRect(10, 30, 221, 21))
        self.label_HAVE_title_currencies.setFrameShape(QtWidgets.QFrame.Box)
        self.label_HAVE_title_currencies.setAlignment(QtCore.Qt.AlignCenter)
        self.label_HAVE_title_currencies.setObjectName("label_HAVE_title_currencies")
        self.label_HAVE_selected_currency = QtWidgets.QLabel(self.groupbox_HAVE)
        self.label_HAVE_selected_currency.setGeometry(QtCore.QRect(10, 90, 441, 21))
        self.label_HAVE_selected_currency.setFrameShape(QtWidgets.QFrame.Box)
        self.label_HAVE_selected_currency.setText("")
        self.label_HAVE_selected_currency.setAlignment(QtCore.Qt.AlignCenter)
        self.label_HAVE_selected_currency.setObjectName("label_HAVE_selected_currency")
        self.combobox_HAVE_currencies = QtWidgets.QComboBox(self.groupbox_HAVE)
        self.combobox_HAVE_currencies.setGeometry(QtCore.QRect(10, 50, 221, 22))
        self.combobox_HAVE_currencies.setObjectName("combobox_HAVE_currencies")
        self.currency_icons = []

        def add_currency_icon(abbreviation: str):
            Icon = QtGui.QIcon()
            Icon.addPixmap(
                QtGui.QPixmap(f":/currencies/images/Currencies/{abbreviation.lower()}.png"),
                QtGui.QIcon.Normal,
                QtGui.QIcon.Off
            )
            self.currency_icons.append(Icon)
            self.combobox_HAVE_currencies.addItem(Icon, "")

        for currency in currencies.currencies:
            add_currency_icon(abbreviation=currency['abbreviation'])
        self.label_HAVE_title_crypto_currencies = QtWidgets.QLabel(self.groupbox_HAVE)
        self.label_HAVE_title_crypto_currencies.setGeometry(QtCore.QRect(230, 30, 221, 21))
        self.label_HAVE_title_crypto_currencies.setFrameShape(QtWidgets.QFrame.Box)
        self.label_HAVE_title_crypto_currencies.setAlignment(QtCore.Qt.AlignCenter)
        self.label_HAVE_title_crypto_currencies.setObjectName("label_HAVE_title_crypto_currencies")
        self.combobox_HAVE_crypto_currencies = QtWidgets.QComboBox(self.groupbox_HAVE)
        self.combobox_HAVE_crypto_currencies.setGeometry(QtCore.QRect(230, 50, 221, 22))
        self.combobox_HAVE_crypto_currencies.setObjectName("combobox_HAVE_crypto_currencies")
        icon162 = QtGui.QIcon()
        icon162.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/btc.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon162, "")
        icon163 = QtGui.QIcon()
        icon163.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/eth.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon163, "")
        icon164 = QtGui.QIcon()
        icon164.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/ada.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon164, "")
        icon165 = QtGui.QIcon()
        icon165.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/bnb.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon165, "")
        icon166 = QtGui.QIcon()
        icon166.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/usdt.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon166, "")
        icon167 = QtGui.QIcon()
        icon167.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/sol.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon167, "")
        icon168 = QtGui.QIcon()
        icon168.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/xrp.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon168, "")
        icon169 = QtGui.QIcon()
        icon169.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/doge.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon169, "")
        icon170 = QtGui.QIcon()
        icon170.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/dot.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon170, "")
        icon171 = QtGui.QIcon()
        icon171.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/usdc.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon171, "")
        icon172 = QtGui.QIcon()
        icon172.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/luna.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon172, "")
        icon173 = QtGui.QIcon()
        icon173.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/uni.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon173, "")
        icon174 = QtGui.QIcon()
        icon174.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/link.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon174, "")
        icon175 = QtGui.QIcon()
        icon175.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/busd.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon175, "")
        icon176 = QtGui.QIcon()
        icon176.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/bch.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon176, "")
        icon177 = QtGui.QIcon()
        icon177.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/ltc.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon177, "")
        icon178 = QtGui.QIcon()
        icon178.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/algo.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon178, "")
        icon179 = QtGui.QIcon()
        icon179.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/avax.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon179, "")
        icon180 = QtGui.QIcon()
        icon180.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/icp.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon180, "")
        icon181 = QtGui.QIcon()
        icon181.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/wbtc.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon181, "")
        icon182 = QtGui.QIcon()
        icon182.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/matic.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon182, "")
        icon183 = QtGui.QIcon()
        icon183.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/ftt.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon183, "")
        icon184 = QtGui.QIcon()
        icon184.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/fil.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon184, "")
        icon185 = QtGui.QIcon()
        icon185.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/xlm.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon185, "")
        icon186 = QtGui.QIcon()
        icon186.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/vet.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon186, "")
        icon187 = QtGui.QIcon()
        icon187.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/etc.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon187, "")
        icon188 = QtGui.QIcon()
        icon188.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/theta.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon188, "")
        icon189 = QtGui.QIcon()
        icon189.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/dai.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon189, "")
        icon190 = QtGui.QIcon()
        icon190.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/trx.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon190, "")
        icon191 = QtGui.QIcon()
        icon191.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/atom.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon191, "")
        icon192 = QtGui.QIcon()
        icon192.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/xtz.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon192, "")
        icon193 = QtGui.QIcon()
        icon193.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/xmr.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon193, "")
        icon194 = QtGui.QIcon()
        icon194.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/miota.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon194, "")
        icon195 = QtGui.QIcon()
        icon195.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/eos.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon195, "")
        icon196 = QtGui.QIcon()
        icon196.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/xec.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon196, "")
        icon197 = QtGui.QIcon()
        icon197.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/cro.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon197, "")
        icon198 = QtGui.QIcon()
        icon198.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/cake.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon198, "")
        icon199 = QtGui.QIcon()
        icon199.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/egld.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon199, "")
        icon200 = QtGui.QIcon()
        icon200.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/aave.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon200, "")
        icon201 = QtGui.QIcon()
        icon201.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/near.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon201, "")
        icon202 = QtGui.QIcon()
        icon202.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/axs.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon202, "")
        icon203 = QtGui.QIcon()
        icon203.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/ftm.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon203, "")
        icon204 = QtGui.QIcon()
        icon204.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/grt.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon204, "")
        icon205 = QtGui.QIcon()
        icon205.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/qnt.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon205, "")
        icon206 = QtGui.QIcon()
        icon206.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/btcb.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon206, "")
        icon207 = QtGui.QIcon()
        icon207.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/neo.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon207, "")
        icon208 = QtGui.QIcon()
        icon208.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/klay.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon208, "")
        icon209 = QtGui.QIcon()
        icon209.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/ksm.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon209, "")
        icon210 = QtGui.QIcon()
        icon210.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/waves.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon210, "")
        icon211 = QtGui.QIcon()
        icon211.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/hbar.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon211, "")
        icon212 = QtGui.QIcon()
        icon212.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/bsv.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon212, "")
        icon213 = QtGui.QIcon()
        icon213.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/leo.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon213, "")
        icon214 = QtGui.QIcon()
        icon214.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/mkr.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon214, "")
        icon215 = QtGui.QIcon()
        icon215.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/shib.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon215, "")
        icon216 = QtGui.QIcon()
        icon216.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/btt.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon216, "")
        icon217 = QtGui.QIcon()
        icon217.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/ust.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon217, "")
        icon218 = QtGui.QIcon()
        icon218.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/ht.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon218, "")
        icon219 = QtGui.QIcon()
        icon219.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/amp.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon219, "")
        icon220 = QtGui.QIcon()
        icon220.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/comp.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon220, "")
        icon221 = QtGui.QIcon()
        icon221.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/ar.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon221, "")
        icon222 = QtGui.QIcon()
        icon222.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/dash.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon222, "")
        icon223 = QtGui.QIcon()
        icon223.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/rev.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon223, "")
        icon224 = QtGui.QIcon()
        icon224.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/chz.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon224, "")
        icon225 = QtGui.QIcon()
        icon225.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/dcr.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon225, "")
        icon226 = QtGui.QIcon()
        icon226.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/rune.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon226, "")
        icon227 = QtGui.QIcon()
        icon227.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/hnt.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon227, "")
        icon228 = QtGui.QIcon()
        icon228.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/one.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon228, "")
        icon229 = QtGui.QIcon()
        icon229.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/stx.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon229, "")
        icon230 = QtGui.QIcon()
        icon230.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/hot.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon230, "")
        icon231 = QtGui.QIcon()
        icon231.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/zec.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon231, "")
        icon232 = QtGui.QIcon()
        icon232.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/tfuel.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon232, "")
        icon233 = QtGui.QIcon()
        icon233.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/xem.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon233, "")
        icon234 = QtGui.QIcon()
        icon234.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/celo.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon234, "")
        icon235 = QtGui.QIcon()
        icon235.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/xdc.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon235, "")
        icon236 = QtGui.QIcon()
        icon236.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/mana.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon236, "")
        icon237 = QtGui.QIcon()
        icon237.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/enj.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon237, "")
        icon238 = QtGui.QIcon()
        icon238.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/tusd.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon238, "")
        icon239 = QtGui.QIcon()
        icon239.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/iost.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon239, "")
        icon240 = QtGui.QIcon()
        icon240.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/cel.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon240, "")
        icon241 = QtGui.QIcon()
        icon241.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/sushi.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon241, "")
        icon242 = QtGui.QIcon()
        icon242.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/zil.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon242, "")
        icon243 = QtGui.QIcon()
        icon243.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/qtum.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon243, "")
        icon244 = QtGui.QIcon()
        icon244.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/snx.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon244, "")
        icon245 = QtGui.QIcon()
        icon245.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/icx.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon245, "")
        icon246 = QtGui.QIcon()
        icon246.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/yfi.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon246, "")
        icon247 = QtGui.QIcon()
        icon247.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/mdx.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon247, "")
        icon248 = QtGui.QIcon()
        icon248.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/mina.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon248, "")
        icon249 = QtGui.QIcon()
        icon249.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/omg.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon249, "")
        icon250 = QtGui.QIcon()
        icon250.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/btg.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon250, "")
        icon251 = QtGui.QIcon()
        icon251.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/flow.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon251, "")
        icon252 = QtGui.QIcon()
        icon252.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/bat.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon252, "")
        icon253 = QtGui.QIcon()
        icon253.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/rvn.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon253, "")
        icon254 = QtGui.QIcon()
        icon254.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/okb.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon254, "")
        icon255 = QtGui.QIcon()
        icon255.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/tel.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon255, "")
        icon256 = QtGui.QIcon()
        icon256.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/audio.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon256, "")
        icon257 = QtGui.QIcon()
        icon257.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/perp.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon257, "")
        icon258 = QtGui.QIcon()
        icon258.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/zen.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon258, "")
        icon259 = QtGui.QIcon()
        icon259.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/bnt.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon259, "")
        icon260 = QtGui.QIcon()
        icon260.addPixmap(QtGui.QPixmap(":/crypto currencies/images/Crypto Currencies/sc.png"), QtGui.QIcon.Normal,
                          QtGui.QIcon.Off)
        self.combobox_HAVE_crypto_currencies.addItem(icon260, "")
        self.lineedit_HAVE_input = QtWidgets.QLineEdit(self.groupbox_HAVE)
        self.lineedit_HAVE_input.setGeometry(QtCore.QRect(10, 110, 441, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineedit_HAVE_input.setFont(font)
        self.lineedit_HAVE_input.setInputMethodHints(QtCore.Qt.ImhDigitsOnly | QtCore.Qt.ImhFormattedNumbersOnly)
        self.lineedit_HAVE_input.setInputMask("")
        self.lineedit_HAVE_input.setText("")
        self.lineedit_HAVE_input.setMaxLength(36)
        self.lineedit_HAVE_input.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineedit_HAVE_input.setAlignment(QtCore.Qt.AlignCenter)
        self.lineedit_HAVE_input.setClearButtonEnabled(False)
        self.lineedit_HAVE_input.setObjectName("lineedit_HAVE_input")
        self.verticalLayout.addWidget(self.groupbox_HAVE)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.button_change = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_change.setObjectName("button_change")
        self.horizontalLayout.addWidget(self.button_change)
        self.button_convert = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_convert.setObjectName("button_convert")
        self.horizontalLayout.addWidget(self.button_convert)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupbox_WANT = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupbox_WANT.setObjectName("groupbox_WANT")
        self.label_WANT_title_currencies = QtWidgets.QLabel(self.groupbox_WANT)
        self.label_WANT_title_currencies.setGeometry(QtCore.QRect(10, 30, 221, 21))
        self.label_WANT_title_currencies.setFrameShape(QtWidgets.QFrame.Box)
        self.label_WANT_title_currencies.setAlignment(QtCore.Qt.AlignCenter)
        self.label_WANT_title_currencies.setObjectName("label_WANT_title_currencies")
        self.label_WANT_title_crypto_currencies = QtWidgets.QLabel(self.groupbox_WANT)
        self.label_WANT_title_crypto_currencies.setGeometry(QtCore.QRect(230, 30, 221, 21))
        self.label_WANT_title_crypto_currencies.setFrameShape(QtWidgets.QFrame.Box)
        self.label_WANT_title_crypto_currencies.setAlignment(QtCore.Qt.AlignCenter)
        self.label_WANT_title_crypto_currencies.setObjectName("label_WANT_title_crypto_currencies")
        self.combobox_WANT_currencies = QtWidgets.QComboBox(self.groupbox_WANT)
        self.combobox_WANT_currencies.setGeometry(QtCore.QRect(10, 50, 221, 22))
        self.combobox_WANT_currencies.setObjectName("combobox_WANT_currencies")
        for icon_ in self.currency_icons:
            self.combobox_WANT_currencies.addItem(icon_, "")
        self.combobox_WANT_crypto_currencies = QtWidgets.QComboBox(self.groupbox_WANT)
        self.combobox_WANT_crypto_currencies.setGeometry(QtCore.QRect(230, 50, 221, 22))
        self.combobox_WANT_crypto_currencies.setObjectName("combobox_WANT_crypto_currencies")
        self.combobox_WANT_crypto_currencies.addItem(icon162, "")
        self.combobox_WANT_crypto_currencies.addItem(icon163, "")
        self.combobox_WANT_crypto_currencies.addItem(icon164, "")
        self.combobox_WANT_crypto_currencies.addItem(icon165, "")
        self.combobox_WANT_crypto_currencies.addItem(icon166, "")
        self.combobox_WANT_crypto_currencies.addItem(icon167, "")
        self.combobox_WANT_crypto_currencies.addItem(icon168, "")
        self.combobox_WANT_crypto_currencies.addItem(icon169, "")
        self.combobox_WANT_crypto_currencies.addItem(icon170, "")
        self.combobox_WANT_crypto_currencies.addItem(icon171, "")
        self.combobox_WANT_crypto_currencies.addItem(icon172, "")
        self.combobox_WANT_crypto_currencies.addItem(icon173, "")
        self.combobox_WANT_crypto_currencies.addItem(icon174, "")
        self.combobox_WANT_crypto_currencies.addItem(icon175, "")
        self.combobox_WANT_crypto_currencies.addItem(icon176, "")
        self.combobox_WANT_crypto_currencies.addItem(icon177, "")
        self.combobox_WANT_crypto_currencies.addItem(icon178, "")
        self.combobox_WANT_crypto_currencies.addItem(icon179, "")
        self.combobox_WANT_crypto_currencies.addItem(icon180, "")
        self.combobox_WANT_crypto_currencies.addItem(icon181, "")
        self.combobox_WANT_crypto_currencies.addItem(icon182, "")
        self.combobox_WANT_crypto_currencies.addItem(icon183, "")
        self.combobox_WANT_crypto_currencies.addItem(icon184, "")
        self.combobox_WANT_crypto_currencies.addItem(icon185, "")
        self.combobox_WANT_crypto_currencies.addItem(icon186, "")
        self.combobox_WANT_crypto_currencies.addItem(icon187, "")
        self.combobox_WANT_crypto_currencies.addItem(icon188, "")
        self.combobox_WANT_crypto_currencies.addItem(icon189, "")
        self.combobox_WANT_crypto_currencies.addItem(icon190, "")
        self.combobox_WANT_crypto_currencies.addItem(icon191, "")
        self.combobox_WANT_crypto_currencies.addItem(icon192, "")
        self.combobox_WANT_crypto_currencies.addItem(icon193, "")
        self.combobox_WANT_crypto_currencies.addItem(icon194, "")
        self.combobox_WANT_crypto_currencies.addItem(icon195, "")
        self.combobox_WANT_crypto_currencies.addItem(icon196, "")
        self.combobox_WANT_crypto_currencies.addItem(icon197, "")
        self.combobox_WANT_crypto_currencies.addItem(icon198, "")
        self.combobox_WANT_crypto_currencies.addItem(icon199, "")
        self.combobox_WANT_crypto_currencies.addItem(icon200, "")
        self.combobox_WANT_crypto_currencies.addItem(icon201, "")
        self.combobox_WANT_crypto_currencies.addItem(icon202, "")
        self.combobox_WANT_crypto_currencies.addItem(icon203, "")
        self.combobox_WANT_crypto_currencies.addItem(icon204, "")
        self.combobox_WANT_crypto_currencies.addItem(icon205, "")
        self.combobox_WANT_crypto_currencies.addItem(icon206, "")
        self.combobox_WANT_crypto_currencies.addItem(icon207, "")
        self.combobox_WANT_crypto_currencies.addItem(icon208, "")
        self.combobox_WANT_crypto_currencies.addItem(icon209, "")
        self.combobox_WANT_crypto_currencies.addItem(icon210, "")
        self.combobox_WANT_crypto_currencies.addItem(icon211, "")
        self.combobox_WANT_crypto_currencies.addItem(icon212, "")
        self.combobox_WANT_crypto_currencies.addItem(icon213, "")
        self.combobox_WANT_crypto_currencies.addItem(icon214, "")
        self.combobox_WANT_crypto_currencies.addItem(icon215, "")
        self.combobox_WANT_crypto_currencies.addItem(icon216, "")
        self.combobox_WANT_crypto_currencies.addItem(icon217, "")
        self.combobox_WANT_crypto_currencies.addItem(icon218, "")
        self.combobox_WANT_crypto_currencies.addItem(icon219, "")
        self.combobox_WANT_crypto_currencies.addItem(icon220, "")
        self.combobox_WANT_crypto_currencies.addItem(icon221, "")
        self.combobox_WANT_crypto_currencies.addItem(icon222, "")
        self.combobox_WANT_crypto_currencies.addItem(icon223, "")
        self.combobox_WANT_crypto_currencies.addItem(icon224, "")
        self.combobox_WANT_crypto_currencies.addItem(icon225, "")
        self.combobox_WANT_crypto_currencies.addItem(icon226, "")
        self.combobox_WANT_crypto_currencies.addItem(icon227, "")
        self.combobox_WANT_crypto_currencies.addItem(icon228, "")
        self.combobox_WANT_crypto_currencies.addItem(icon229, "")
        self.combobox_WANT_crypto_currencies.addItem(icon230, "")
        self.combobox_WANT_crypto_currencies.addItem(icon231, "")
        self.combobox_WANT_crypto_currencies.addItem(icon232, "")
        self.combobox_WANT_crypto_currencies.addItem(icon233, "")
        self.combobox_WANT_crypto_currencies.addItem(icon234, "")
        self.combobox_WANT_crypto_currencies.addItem(icon235, "")
        self.combobox_WANT_crypto_currencies.addItem(icon236, "")
        self.combobox_WANT_crypto_currencies.addItem(icon237, "")
        self.combobox_WANT_crypto_currencies.addItem(icon238, "")
        self.combobox_WANT_crypto_currencies.addItem(icon239, "")
        self.combobox_WANT_crypto_currencies.addItem(icon240, "")
        self.combobox_WANT_crypto_currencies.addItem(icon241, "")
        self.combobox_WANT_crypto_currencies.addItem(icon242, "")
        self.combobox_WANT_crypto_currencies.addItem(icon243, "")
        self.combobox_WANT_crypto_currencies.addItem(icon244, "")
        self.combobox_WANT_crypto_currencies.addItem(icon245, "")
        self.combobox_WANT_crypto_currencies.addItem(icon246, "")
        self.combobox_WANT_crypto_currencies.addItem(icon247, "")
        self.combobox_WANT_crypto_currencies.addItem(icon248, "")
        self.combobox_WANT_crypto_currencies.addItem(icon249, "")
        self.combobox_WANT_crypto_currencies.addItem(icon250, "")
        self.combobox_WANT_crypto_currencies.addItem(icon251, "")
        self.combobox_WANT_crypto_currencies.addItem(icon252, "")
        self.combobox_WANT_crypto_currencies.addItem(icon253, "")
        self.combobox_WANT_crypto_currencies.addItem(icon254, "")
        self.combobox_WANT_crypto_currencies.addItem(icon255, "")
        self.combobox_WANT_crypto_currencies.addItem(icon256, "")
        self.combobox_WANT_crypto_currencies.addItem(icon257, "")
        self.combobox_WANT_crypto_currencies.addItem(icon258, "")
        self.combobox_WANT_crypto_currencies.addItem(icon259, "")
        self.combobox_WANT_crypto_currencies.addItem(icon260, "")
        self.label_WANT_selected_currency = QtWidgets.QLabel(self.groupbox_WANT)
        self.label_WANT_selected_currency.setGeometry(QtCore.QRect(10, 90, 441, 21))
        self.label_WANT_selected_currency.setFrameShape(QtWidgets.QFrame.Box)
        self.label_WANT_selected_currency.setText("")
        self.label_WANT_selected_currency.setAlignment(QtCore.Qt.AlignCenter)
        self.label_WANT_selected_currency.setObjectName("label_WANT_selected_currency")
        self.lineedit_WANT_output = QtWidgets.QLineEdit(self.groupbox_WANT)
        self.lineedit_WANT_output.setGeometry(QtCore.QRect(10, 110, 441, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineedit_WANT_output.setFont(font)
        self.lineedit_WANT_output.setInputMethodHints(QtCore.Qt.ImhDigitsOnly | QtCore.Qt.ImhFormattedNumbersOnly)
        self.lineedit_WANT_output.setInputMask("")
        self.lineedit_WANT_output.setText("")
        self.lineedit_WANT_output.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineedit_WANT_output.setAlignment(QtCore.Qt.AlignCenter)
        self.lineedit_WANT_output.setReadOnly(True)
        self.lineedit_WANT_output.setClearButtonEnabled(False)
        self.lineedit_WANT_output.setObjectName("lineedit_WANT_output")
        self.verticalLayout.addWidget(self.groupbox_WANT)
        self.verticalLayout.setStretch(0, 45)
        self.verticalLayout.setStretch(1, 10)
        self.verticalLayout.setStretch(2, 45)
        self.lbl_copyright = QtWidgets.QLabel(self.centralwidget)
        self.lbl_copyright.setGeometry(QtCore.QRect(0, 380, 501, 20))
        self.lbl_copyright.setStyleSheet("color: rgb(0, 0, 0);")
        self.lbl_copyright.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_copyright.setObjectName("lbl_copyright")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.combobox_HAVE_currencies.setCurrentIndex(-1)
        self.combobox_HAVE_crypto_currencies.setCurrentIndex(-1)
        self.combobox_WANT_currencies.setCurrentIndex(-1)
        self.combobox_WANT_crypto_currencies.setCurrentIndex(-1)
        self.combobox_HAVE_currencies.currentIndexChanged['QString'].connect(self.label_HAVE_selected_currency.setText)
        self.combobox_HAVE_crypto_currencies.currentIndexChanged['QString'].connect(
            self.label_HAVE_selected_currency.setText)
        self.combobox_WANT_currencies.currentIndexChanged['QString'].connect(self.label_WANT_selected_currency.setText)
        self.combobox_WANT_crypto_currencies.currentIndexChanged['QString'].connect(
            self.label_WANT_selected_currency.setText)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Currency Converter"))
        self.groupbox_HAVE.setTitle(_translate("MainWindow", "Currency I Have"))
        self.label_HAVE_title_currencies.setText(_translate("MainWindow", "Currencies"))
        self.combobox_HAVE_currencies.setItemText(0, _translate("MainWindow", "USD - US Dollar"))
        self.combobox_HAVE_currencies.setItemText(1, _translate("MainWindow", "EUR - Euro"))
        self.combobox_HAVE_currencies.setItemText(2, _translate("MainWindow", "JPY - Japanese Yen"))
        self.combobox_HAVE_currencies.setItemText(3, _translate("MainWindow", "GBP - British Pound Sterling"))
        self.combobox_HAVE_currencies.setItemText(4, _translate("MainWindow", "AUD - Australian Dollar"))
        self.combobox_HAVE_currencies.setItemText(5, _translate("MainWindow", "CAD - Canadian Dollar"))
        self.combobox_HAVE_currencies.setItemText(6, _translate("MainWindow", "CHF - Swiss Franc"))
        self.combobox_HAVE_currencies.setItemText(7, _translate("MainWindow", "CNY - Chinese Yuan"))
        self.combobox_HAVE_currencies.setItemText(8, _translate("MainWindow", "SEK - Swedish Krona"))
        self.combobox_HAVE_currencies.setItemText(9, _translate("MainWindow", "NZD - New Zealand Dollar"))
        self.combobox_HAVE_currencies.setItemText(10, _translate("MainWindow", "AED - Arab Emirates Dirham"))
        self.combobox_HAVE_currencies.setItemText(11, _translate("MainWindow", "AFN - Afghan Afghani"))
        self.combobox_HAVE_currencies.setItemText(12, _translate("MainWindow", "ALL - Albania Lek"))
        self.combobox_HAVE_currencies.setItemText(13, _translate("MainWindow", "AMD - Armenian Dram"))
        self.combobox_HAVE_currencies.setItemText(14, _translate("MainWindow", "ANG - Netherlands Antillean Guilder"))
        self.combobox_HAVE_currencies.setItemText(15, _translate("MainWindow", "AOA - Angolan Kwanza"))
        self.combobox_HAVE_currencies.setItemText(16, _translate("MainWindow", "ARS - Argentine Peso"))
        self.combobox_HAVE_currencies.setItemText(17, _translate("MainWindow", "AWG - Aruban Florin"))
        self.combobox_HAVE_currencies.setItemText(18, _translate("MainWindow", "AZN - Azerbaijani Manat"))
        self.combobox_HAVE_currencies.setItemText(19,
                                                  _translate("MainWindow", "BAM - Bosnia-Herzegovina Convertible Mark"))
        self.combobox_HAVE_currencies.setItemText(20, _translate("MainWindow", "BBD - Barbadian Dollar"))
        self.combobox_HAVE_currencies.setItemText(21, _translate("MainWindow", "BDT - Bangladeshi Taka"))
        self.combobox_HAVE_currencies.setItemText(22, _translate("MainWindow", "BGN - Bulgarian Lev"))
        self.combobox_HAVE_currencies.setItemText(23, _translate("MainWindow", "BHD - Bahraini Dinar"))
        self.combobox_HAVE_currencies.setItemText(24, _translate("MainWindow", "BIF - Burundian Franc"))
        self.combobox_HAVE_currencies.setItemText(25, _translate("MainWindow", "BMD - Bermudan Dollar"))
        self.combobox_HAVE_currencies.setItemText(26, _translate("MainWindow", "BND - Brunei Dollar"))
        self.combobox_HAVE_currencies.setItemText(27, _translate("MainWindow", "BOB - Bolivian Boliviano"))
        self.combobox_HAVE_currencies.setItemText(28, _translate("MainWindow", "BRL - Brazilian Real"))
        self.combobox_HAVE_currencies.setItemText(29, _translate("MainWindow", "BSD - Bahamian Dollar"))
        self.combobox_HAVE_currencies.setItemText(30, _translate("MainWindow", "BTN - Bhutanese Ngultrum"))
        self.combobox_HAVE_currencies.setItemText(31, _translate("MainWindow", "BWP - Botswanan Pula"))
        self.combobox_HAVE_currencies.setItemText(32, _translate("MainWindow", "BYR - Belarusian Ruble"))
        self.combobox_HAVE_currencies.setItemText(33, _translate("MainWindow", "BZD - Belize Dollar"))
        self.combobox_HAVE_currencies.setItemText(34, _translate("MainWindow", "CDF - Congolese Franc"))
        self.combobox_HAVE_currencies.setItemText(35, _translate("MainWindow", "CLF - Chilean Unit of Account"))
        self.combobox_HAVE_currencies.setItemText(36, _translate("MainWindow", "CLP - Chilean Peso"))
        self.combobox_HAVE_currencies.setItemText(37, _translate("MainWindow", "COP - Colombian Peso"))
        self.combobox_HAVE_currencies.setItemText(38, _translate("MainWindow", "CRC - Costa Rican Colón"))
        self.combobox_HAVE_currencies.setItemText(39, _translate("MainWindow", "CUC - Cuban Convertible Peso"))
        self.combobox_HAVE_currencies.setItemText(40, _translate("MainWindow", "CUP - Cuban Peso"))
        self.combobox_HAVE_currencies.setItemText(41, _translate("MainWindow", "CVE - Cape Verdean Escudo"))
        self.combobox_HAVE_currencies.setItemText(42, _translate("MainWindow", "CZK - Czech Republic Koruna"))
        self.combobox_HAVE_currencies.setItemText(43, _translate("MainWindow", "DJF - Djiboutian Franc"))
        self.combobox_HAVE_currencies.setItemText(44, _translate("MainWindow", "DKK - Danish Krone"))
        self.combobox_HAVE_currencies.setItemText(45, _translate("MainWindow", "DOP - Dominican Peso"))
        self.combobox_HAVE_currencies.setItemText(46, _translate("MainWindow", "DZD - Algerian Dinar"))
        self.combobox_HAVE_currencies.setItemText(47, _translate("MainWindow", "EGP - Egyptian Pound"))
        self.combobox_HAVE_currencies.setItemText(48, _translate("MainWindow", "ERN - Eritrean Nakfa"))
        self.combobox_HAVE_currencies.setItemText(49, _translate("MainWindow", "ETB - Ethiopian Birr"))
        self.combobox_HAVE_currencies.setItemText(50, _translate("MainWindow", "FJD - Fijian Dollar"))
        self.combobox_HAVE_currencies.setItemText(51, _translate("MainWindow", "FKP - Falkland Islands Pound"))
        self.combobox_HAVE_currencies.setItemText(52, _translate("MainWindow", "GEL - Georgian Lari"))
        self.combobox_HAVE_currencies.setItemText(53, _translate("MainWindow", "GHS - Ghanaian Cedi"))
        self.combobox_HAVE_currencies.setItemText(54, _translate("MainWindow", "GIP - Gibraltar Pound"))
        self.combobox_HAVE_currencies.setItemText(55, _translate("MainWindow", "GMD - Gambian Dalasi"))
        self.combobox_HAVE_currencies.setItemText(56, _translate("MainWindow", "GNF - Guinean Franc"))
        self.combobox_HAVE_currencies.setItemText(57, _translate("MainWindow", "GTQ - Guatemalan Quetzal"))
        self.combobox_HAVE_currencies.setItemText(58, _translate("MainWindow", "GYD - Guyanaese Dollar"))
        self.combobox_HAVE_currencies.setItemText(59, _translate("MainWindow", "HKD - Hong Kong Dollar"))
        self.combobox_HAVE_currencies.setItemText(60, _translate("MainWindow", "HNL - Honduran Lempira"))
        self.combobox_HAVE_currencies.setItemText(61, _translate("MainWindow", "HRK - Croatian Kuna"))
        self.combobox_HAVE_currencies.setItemText(62, _translate("MainWindow", "HTG - Haitian Gourde"))
        self.combobox_HAVE_currencies.setItemText(63, _translate("MainWindow", "HUF - Hungarian Forint"))
        self.combobox_HAVE_currencies.setItemText(64, _translate("MainWindow", "IDR - Indonesian Rupiah"))
        self.combobox_HAVE_currencies.setItemText(65, _translate("MainWindow", "ILS - Israeli New Sheqel"))
        self.combobox_HAVE_currencies.setItemText(66, _translate("MainWindow", "IMP - Manx pound"))
        self.combobox_HAVE_currencies.setItemText(67, _translate("MainWindow", "INR - Indian Rupee"))
        self.combobox_HAVE_currencies.setItemText(68, _translate("MainWindow", "IQD - Iraqi Dinar"))
        self.combobox_HAVE_currencies.setItemText(69, _translate("MainWindow", "IRR - Iranian Rial"))
        self.combobox_HAVE_currencies.setItemText(70, _translate("MainWindow", "ISK - Icelandic Króna"))
        self.combobox_HAVE_currencies.setItemText(71, _translate("MainWindow", "JEP - Jersey Pound"))
        self.combobox_HAVE_currencies.setItemText(72, _translate("MainWindow", "JMD - Jamaican Dollar"))
        self.combobox_HAVE_currencies.setItemText(73, _translate("MainWindow", "JOD - Jordanian Dinar"))
        self.combobox_HAVE_currencies.setItemText(74, _translate("MainWindow", "KES - Kenyan Shilling"))
        self.combobox_HAVE_currencies.setItemText(75, _translate("MainWindow", "KGS - Kyrgystani Som"))
        self.combobox_HAVE_currencies.setItemText(76, _translate("MainWindow", "KHR - Cambodian Riel"))
        self.combobox_HAVE_currencies.setItemText(77, _translate("MainWindow", "KMF - Comorian Franc"))
        self.combobox_HAVE_currencies.setItemText(78, _translate("MainWindow", "KPW - North Korean Won"))
        self.combobox_HAVE_currencies.setItemText(79, _translate("MainWindow", "KRW - South Korean Won"))
        self.combobox_HAVE_currencies.setItemText(80, _translate("MainWindow", "KWD - Kuwaiti Dinar"))
        self.combobox_HAVE_currencies.setItemText(81, _translate("MainWindow", "KYD - Cayman Islands Dollar"))
        self.combobox_HAVE_currencies.setItemText(82, _translate("MainWindow", "KZT - Kazakhstani Tenge"))
        self.combobox_HAVE_currencies.setItemText(83, _translate("MainWindow", "LAK - Laotian Kip"))
        self.combobox_HAVE_currencies.setItemText(84, _translate("MainWindow", "LBP - Lebanese Pound"))
        self.combobox_HAVE_currencies.setItemText(85, _translate("MainWindow", "LKR - Sri Lankan Rupee"))
        self.combobox_HAVE_currencies.setItemText(86, _translate("MainWindow", "LRD - Liberian Dollar"))
        self.combobox_HAVE_currencies.setItemText(87, _translate("MainWindow", "LSL - Lesotho Loti"))
        self.combobox_HAVE_currencies.setItemText(88, _translate("MainWindow", "LTL - Lithuanian Litas"))
        self.combobox_HAVE_currencies.setItemText(89, _translate("MainWindow", "LVL - Latvian Lats"))
        self.combobox_HAVE_currencies.setItemText(90, _translate("MainWindow", "LYD - Libyan Dinar"))
        self.combobox_HAVE_currencies.setItemText(91, _translate("MainWindow", "MAD - Moroccan Dirham"))
        self.combobox_HAVE_currencies.setItemText(92, _translate("MainWindow", "MDL - Moldovan Leu"))
        self.combobox_HAVE_currencies.setItemText(93, _translate("MainWindow", "MGA - Malagasy Ariary"))
        self.combobox_HAVE_currencies.setItemText(94, _translate("MainWindow", "MKD - Macedonian Denar"))
        self.combobox_HAVE_currencies.setItemText(95, _translate("MainWindow", "MMK - Myanma Kyat"))
        self.combobox_HAVE_currencies.setItemText(96, _translate("MainWindow", "MNT - Mongolian Tugrik"))
        self.combobox_HAVE_currencies.setItemText(97, _translate("MainWindow", "MOP - Macanese Pataca"))
        self.combobox_HAVE_currencies.setItemText(98, _translate("MainWindow", "MRO - Mauritanian Ouguiya"))
        self.combobox_HAVE_currencies.setItemText(99, _translate("MainWindow", "MUR - Mauritian Rupee"))
        self.combobox_HAVE_currencies.setItemText(100, _translate("MainWindow", "MVR - Maldivian Rufiyaa"))
        self.combobox_HAVE_currencies.setItemText(101, _translate("MainWindow", "MWK - Malawian Kwacha"))
        self.combobox_HAVE_currencies.setItemText(102, _translate("MainWindow", "MXN - Mexican Peso"))
        self.combobox_HAVE_currencies.setItemText(103, _translate("MainWindow", "MYR - Malaysian Ringgit"))
        self.combobox_HAVE_currencies.setItemText(104, _translate("MainWindow", "MZN - Mozambican Metical"))
        self.combobox_HAVE_currencies.setItemText(105, _translate("MainWindow", "NAD - Namibian Dollar"))
        self.combobox_HAVE_currencies.setItemText(106, _translate("MainWindow", "NGN - Nigerian Naira"))
        self.combobox_HAVE_currencies.setItemText(107, _translate("MainWindow", "NIO - Nicaraguan Córdoba"))
        self.combobox_HAVE_currencies.setItemText(108, _translate("MainWindow", "NOK - Norwegian Krone"))
        self.combobox_HAVE_currencies.setItemText(109, _translate("MainWindow", "NPR - Nepalese Rupee"))
        self.combobox_HAVE_currencies.setItemText(110, _translate("MainWindow", "OMR - Omani Rial"))
        self.combobox_HAVE_currencies.setItemText(111, _translate("MainWindow", "PAB - Panamanian Balboa"))
        self.combobox_HAVE_currencies.setItemText(112, _translate("MainWindow", "PEN - Peruvian Nuevo Sol"))
        self.combobox_HAVE_currencies.setItemText(113, _translate("MainWindow", "PGK - Papua New Guinean Kina"))
        self.combobox_HAVE_currencies.setItemText(114, _translate("MainWindow", "PHP - Philippine Peso"))
        self.combobox_HAVE_currencies.setItemText(115, _translate("MainWindow", "PKR - Pakistani Rupee"))
        self.combobox_HAVE_currencies.setItemText(116, _translate("MainWindow", "PLN - Polish Zloty"))
        self.combobox_HAVE_currencies.setItemText(117, _translate("MainWindow", "PYG - Paraguayan Guarani"))
        self.combobox_HAVE_currencies.setItemText(118, _translate("MainWindow", "QAR - Qatari Rial"))
        self.combobox_HAVE_currencies.setItemText(119, _translate("MainWindow", "RON - Romanian Leu"))
        self.combobox_HAVE_currencies.setItemText(120, _translate("MainWindow", "RSD - Serbian Dinar"))
        self.combobox_HAVE_currencies.setItemText(121, _translate("MainWindow", "RUB - Russian Ruble"))
        self.combobox_HAVE_currencies.setItemText(122, _translate("MainWindow", "RWF - Rwandan Franc"))
        self.combobox_HAVE_currencies.setItemText(123, _translate("MainWindow", "SAR - Saudi Riyal"))
        self.combobox_HAVE_currencies.setItemText(124, _translate("MainWindow", "SBD - Solomon Islands Dollar"))
        self.combobox_HAVE_currencies.setItemText(125, _translate("MainWindow", "SCR - Seychellois Rupee"))
        self.combobox_HAVE_currencies.setItemText(126, _translate("MainWindow", "SDG - Sudanese Pound"))
        self.combobox_HAVE_currencies.setItemText(127, _translate("MainWindow", "SGD - Singapore Dollar"))
        self.combobox_HAVE_currencies.setItemText(128, _translate("MainWindow", "SHP - Saint Helena Pound"))
        self.combobox_HAVE_currencies.setItemText(129, _translate("MainWindow", "SLL - Sierra Leonean Leone"))
        self.combobox_HAVE_currencies.setItemText(130, _translate("MainWindow", "SOS - Somali Shilling"))
        self.combobox_HAVE_currencies.setItemText(131, _translate("MainWindow", "SRD - Surinamese Dollar"))
        self.combobox_HAVE_currencies.setItemText(132, _translate("MainWindow", "STD - São Tomé and Príncipe Dobra"))
        self.combobox_HAVE_currencies.setItemText(133, _translate("MainWindow", "SVC - Salvadoran Colón"))
        self.combobox_HAVE_currencies.setItemText(134, _translate("MainWindow", "SYP - Syrian Pound"))
        self.combobox_HAVE_currencies.setItemText(135, _translate("MainWindow", "SZL - Swazi Lilangeni"))
        self.combobox_HAVE_currencies.setItemText(136, _translate("MainWindow", "THB - Thai Baht"))
        self.combobox_HAVE_currencies.setItemText(137, _translate("MainWindow", "TJS - Tajikistani Somoni"))
        self.combobox_HAVE_currencies.setItemText(138, _translate("MainWindow", "TMT - Turkmenistani Manat"))
        self.combobox_HAVE_currencies.setItemText(139, _translate("MainWindow", "TND - Tunisian Dinar"))
        self.combobox_HAVE_currencies.setItemText(140, _translate("MainWindow", "TOP - Tongan Paʻanga"))
        self.combobox_HAVE_currencies.setItemText(141, _translate("MainWindow", "TRY - Turkish Lira"))
        self.combobox_HAVE_currencies.setItemText(142, _translate("MainWindow", "TTD - Trinidad and Tobago Dollar"))
        self.combobox_HAVE_currencies.setItemText(143, _translate("MainWindow", "TWD - New Taiwan Dollar"))
        self.combobox_HAVE_currencies.setItemText(144, _translate("MainWindow", "TZS - Tanzanian Shilling"))
        self.combobox_HAVE_currencies.setItemText(145, _translate("MainWindow", "UAH - Ukrainian Hryvnia"))
        self.combobox_HAVE_currencies.setItemText(146, _translate("MainWindow", "UGX - Ugandan Shilling"))
        self.combobox_HAVE_currencies.setItemText(147, _translate("MainWindow", "UYU - Uruguayan Peso"))
        self.combobox_HAVE_currencies.setItemText(148, _translate("MainWindow", "UZS - Uzbekistan Som"))
        self.combobox_HAVE_currencies.setItemText(149, _translate("MainWindow", "VEF - Venezuelan Bolívar Fuerte"))
        self.combobox_HAVE_currencies.setItemText(150, _translate("MainWindow", "VND - Vietnamese Dong"))
        self.combobox_HAVE_currencies.setItemText(151, _translate("MainWindow", "VUV - Vanuatu Vatu"))
        self.combobox_HAVE_currencies.setItemText(152, _translate("MainWindow", "WST - Samoan Tala"))
        self.combobox_HAVE_currencies.setItemText(153, _translate("MainWindow", "XAF - CFA Franc BEAC"))
        self.combobox_HAVE_currencies.setItemText(154, _translate("MainWindow", "XCD - East Caribbean Dollar"))
        self.combobox_HAVE_currencies.setItemText(155, _translate("MainWindow", "XOF - CFA Franc BCEAO"))
        self.combobox_HAVE_currencies.setItemText(156, _translate("MainWindow", "XPF - CFP Franc"))
        self.combobox_HAVE_currencies.setItemText(157, _translate("MainWindow", "YER - Yemeni Rial"))
        self.combobox_HAVE_currencies.setItemText(158, _translate("MainWindow", "ZAR - South African Rand"))
        self.combobox_HAVE_currencies.setItemText(159, _translate("MainWindow", "ZMW - Zambian Kwacha"))
        self.combobox_HAVE_currencies.setItemText(160, _translate("MainWindow", "ZWL - Zimbabwean Dollar"))
        self.label_HAVE_title_crypto_currencies.setText(_translate("MainWindow", "Crypto Currencies"))
        self.combobox_HAVE_crypto_currencies.setItemText(0, _translate("MainWindow", "BTC - Bitcoin"))
        self.combobox_HAVE_crypto_currencies.setItemText(1, _translate("MainWindow", "ETH - Ethereum"))
        self.combobox_HAVE_crypto_currencies.setItemText(2, _translate("MainWindow", "ADA - Cardano"))
        self.combobox_HAVE_crypto_currencies.setItemText(3, _translate("MainWindow", "BNB - Binance Coin"))
        self.combobox_HAVE_crypto_currencies.setItemText(4, _translate("MainWindow", "USDT - TETHER"))
        self.combobox_HAVE_crypto_currencies.setItemText(5, _translate("MainWindow", "SOL - Solona"))
        self.combobox_HAVE_crypto_currencies.setItemText(6, _translate("MainWindow", "XRP - Xrp"))
        self.combobox_HAVE_crypto_currencies.setItemText(7, _translate("MainWindow", "DOGE - Dogecoin"))
        self.combobox_HAVE_crypto_currencies.setItemText(8, _translate("MainWindow", "DOT - Polkadot"))
        self.combobox_HAVE_crypto_currencies.setItemText(9, _translate("MainWindow", "USDC - USD Coin"))
        self.combobox_HAVE_crypto_currencies.setItemText(10, _translate("MainWindow", "LUNA - Terra"))
        self.combobox_HAVE_crypto_currencies.setItemText(11, _translate("MainWindow", "UNI - Uniswap"))
        self.combobox_HAVE_crypto_currencies.setItemText(12, _translate("MainWindow", "LINK - Chainlink"))
        self.combobox_HAVE_crypto_currencies.setItemText(13, _translate("MainWindow", "BUSD - Binance USD"))
        self.combobox_HAVE_crypto_currencies.setItemText(14, _translate("MainWindow", "BCH - Bitcoin Cash"))
        self.combobox_HAVE_crypto_currencies.setItemText(15, _translate("MainWindow", "LTC - Litecoin"))
        self.combobox_HAVE_crypto_currencies.setItemText(16, _translate("MainWindow", "ALGO - Algorand"))
        self.combobox_HAVE_crypto_currencies.setItemText(17, _translate("MainWindow", "AVAX - Avalanche"))
        self.combobox_HAVE_crypto_currencies.setItemText(18, _translate("MainWindow", "ICP - Internet Computer"))
        self.combobox_HAVE_crypto_currencies.setItemText(19, _translate("MainWindow", "WBTC - Wrapped Bitcoin"))
        self.combobox_HAVE_crypto_currencies.setItemText(20, _translate("MainWindow", "MATIC - Polygon"))
        self.combobox_HAVE_crypto_currencies.setItemText(21, _translate("MainWindow", "FTT - FTX Token"))
        self.combobox_HAVE_crypto_currencies.setItemText(22, _translate("MainWindow", "FIL - Filecoin"))
        self.combobox_HAVE_crypto_currencies.setItemText(23, _translate("MainWindow", "XLM - Stellar"))
        self.combobox_HAVE_crypto_currencies.setItemText(24, _translate("MainWindow", "VET - VeChain"))
        self.combobox_HAVE_crypto_currencies.setItemText(25, _translate("MainWindow", "ETC - Ethereum Classic"))
        self.combobox_HAVE_crypto_currencies.setItemText(26, _translate("MainWindow", "THETA - Theta"))
        self.combobox_HAVE_crypto_currencies.setItemText(27, _translate("MainWindow", "DAI - Dai"))
        self.combobox_HAVE_crypto_currencies.setItemText(28, _translate("MainWindow", "TRX - Tron"))
        self.combobox_HAVE_crypto_currencies.setItemText(29, _translate("MainWindow", "ATOM - Cosmos"))
        self.combobox_HAVE_crypto_currencies.setItemText(30, _translate("MainWindow", "XTZ - Tezos"))
        self.combobox_HAVE_crypto_currencies.setItemText(31, _translate("MainWindow", "XMR - Monero"))
        self.combobox_HAVE_crypto_currencies.setItemText(32, _translate("MainWindow", "MIOTA - IOTA"))
        self.combobox_HAVE_crypto_currencies.setItemText(33, _translate("MainWindow", "EOS - EOS"))
        self.combobox_HAVE_crypto_currencies.setItemText(34, _translate("MainWindow", "XEC - ECash"))
        self.combobox_HAVE_crypto_currencies.setItemText(35, _translate("MainWindow", "CRO - Crypto.com Coin"))
        self.combobox_HAVE_crypto_currencies.setItemText(36, _translate("MainWindow", "CAKE - PancakeSwap"))
        self.combobox_HAVE_crypto_currencies.setItemText(37, _translate("MainWindow", "EGLD - Elrond"))
        self.combobox_HAVE_crypto_currencies.setItemText(38, _translate("MainWindow", "AAVE - Aave"))
        self.combobox_HAVE_crypto_currencies.setItemText(39, _translate("MainWindow", "NEAR - NEAR Protocol"))
        self.combobox_HAVE_crypto_currencies.setItemText(40, _translate("MainWindow", "AXS - Axie Infinity"))
        self.combobox_HAVE_crypto_currencies.setItemText(41, _translate("MainWindow", "FTM - Fantom"))
        self.combobox_HAVE_crypto_currencies.setItemText(42, _translate("MainWindow", "GRT - The Graph"))
        self.combobox_HAVE_crypto_currencies.setItemText(43, _translate("MainWindow", "QNT - Quant"))
        self.combobox_HAVE_crypto_currencies.setItemText(44, _translate("MainWindow", "BTCB - Bitcoin BEP2"))
        self.combobox_HAVE_crypto_currencies.setItemText(45, _translate("MainWindow", "NEO - Neo"))
        self.combobox_HAVE_crypto_currencies.setItemText(46, _translate("MainWindow", "KLAY - Klaytn"))
        self.combobox_HAVE_crypto_currencies.setItemText(47, _translate("MainWindow", "KSM - Kusama"))
        self.combobox_HAVE_crypto_currencies.setItemText(48, _translate("MainWindow", "WAVES - Waves"))
        self.combobox_HAVE_crypto_currencies.setItemText(49, _translate("MainWindow", "HBAR - Hedera Hashgraph"))
        self.combobox_HAVE_crypto_currencies.setItemText(50, _translate("MainWindow", "BSV - Bitcoin SV"))
        self.combobox_HAVE_crypto_currencies.setItemText(51, _translate("MainWindow", "LEO - UNUS SED LEO"))
        self.combobox_HAVE_crypto_currencies.setItemText(52, _translate("MainWindow", "MKR - Maker"))
        self.combobox_HAVE_crypto_currencies.setItemText(53, _translate("MainWindow", "SHIB - SHIBA INU"))
        self.combobox_HAVE_crypto_currencies.setItemText(54, _translate("MainWindow", "BTT - BitTorrent"))
        self.combobox_HAVE_crypto_currencies.setItemText(55, _translate("MainWindow", "UST - TerraUSD"))
        self.combobox_HAVE_crypto_currencies.setItemText(56, _translate("MainWindow", "HT - Huobi Token"))
        self.combobox_HAVE_crypto_currencies.setItemText(57, _translate("MainWindow", "AMP - Amp"))
        self.combobox_HAVE_crypto_currencies.setItemText(58, _translate("MainWindow", "COMP - Compound"))
        self.combobox_HAVE_crypto_currencies.setItemText(59, _translate("MainWindow", "AR - Arweave"))
        self.combobox_HAVE_crypto_currencies.setItemText(60, _translate("MainWindow", "DASH - Dash"))
        self.combobox_HAVE_crypto_currencies.setItemText(61, _translate("MainWindow", "REV - Revain"))
        self.combobox_HAVE_crypto_currencies.setItemText(62, _translate("MainWindow", "CHZ - Chiliz"))
        self.combobox_HAVE_crypto_currencies.setItemText(63, _translate("MainWindow", "DCR - Decred"))
        self.combobox_HAVE_crypto_currencies.setItemText(64, _translate("MainWindow", "RUNE - THORChain"))
        self.combobox_HAVE_crypto_currencies.setItemText(65, _translate("MainWindow", "HNT - Helium"))
        self.combobox_HAVE_crypto_currencies.setItemText(66, _translate("MainWindow", "ONE - Harmony"))
        self.combobox_HAVE_crypto_currencies.setItemText(67, _translate("MainWindow", "STX - Stacks"))
        self.combobox_HAVE_crypto_currencies.setItemText(68, _translate("MainWindow", "HOT - Holo"))
        self.combobox_HAVE_crypto_currencies.setItemText(69, _translate("MainWindow", "ZEC - Zcash"))
        self.combobox_HAVE_crypto_currencies.setItemText(70, _translate("MainWindow", "TFUEL - Theta Fuel"))
        self.combobox_HAVE_crypto_currencies.setItemText(71, _translate("MainWindow", "XEM - NEM"))
        self.combobox_HAVE_crypto_currencies.setItemText(72, _translate("MainWindow", "CELO - Celo"))
        self.combobox_HAVE_crypto_currencies.setItemText(73, _translate("MainWindow", "XDC - XinFin"))
        self.combobox_HAVE_crypto_currencies.setItemText(74, _translate("MainWindow", "MANA - Decentraland"))
        self.combobox_HAVE_crypto_currencies.setItemText(75, _translate("MainWindow", "ENJ - Enjin Coin"))
        self.combobox_HAVE_crypto_currencies.setItemText(76, _translate("MainWindow", "TUSD - TrueUSD"))
        self.combobox_HAVE_crypto_currencies.setItemText(77, _translate("MainWindow", "IOST - IOST"))
        self.combobox_HAVE_crypto_currencies.setItemText(78, _translate("MainWindow", "CEL - Celsius"))
        self.combobox_HAVE_crypto_currencies.setItemText(79, _translate("MainWindow", "SUSHI - Sushiswap"))
        self.combobox_HAVE_crypto_currencies.setItemText(80, _translate("MainWindow", "ZIL - Zilliqa"))
        self.combobox_HAVE_crypto_currencies.setItemText(81, _translate("MainWindow", "QTUM - Qtum"))
        self.combobox_HAVE_crypto_currencies.setItemText(82, _translate("MainWindow", "SNX - Synthetix"))
        self.combobox_HAVE_crypto_currencies.setItemText(83, _translate("MainWindow", "ICX - ICON"))
        self.combobox_HAVE_crypto_currencies.setItemText(84, _translate("MainWindow", "YFI - Yearn.finance"))
        self.combobox_HAVE_crypto_currencies.setItemText(85, _translate("MainWindow", "MDX - Mdex"))
        self.combobox_HAVE_crypto_currencies.setItemText(86, _translate("MainWindow", "MINA - Mina"))
        self.combobox_HAVE_crypto_currencies.setItemText(87, _translate("MainWindow", "OMG - OMG Network"))
        self.combobox_HAVE_crypto_currencies.setItemText(88, _translate("MainWindow", "BTG - Bitcoin Gold"))
        self.combobox_HAVE_crypto_currencies.setItemText(89, _translate("MainWindow", "FLOW - Flow"))
        self.combobox_HAVE_crypto_currencies.setItemText(90, _translate("MainWindow", "BAT - Basic Attention Token"))
        self.combobox_HAVE_crypto_currencies.setItemText(91, _translate("MainWindow", "RVN - Ravencoin"))
        self.combobox_HAVE_crypto_currencies.setItemText(92, _translate("MainWindow", "OKB - OKB"))
        self.combobox_HAVE_crypto_currencies.setItemText(93, _translate("MainWindow", "TEL - Telcoin"))
        self.combobox_HAVE_crypto_currencies.setItemText(94, _translate("MainWindow", "AUDIO - Audius"))
        self.combobox_HAVE_crypto_currencies.setItemText(95, _translate("MainWindow", "PERP - Curve DAO Token"))
        self.combobox_HAVE_crypto_currencies.setItemText(96, _translate("MainWindow", "ZEN - Horizen"))
        self.combobox_HAVE_crypto_currencies.setItemText(97, _translate("MainWindow", "BNT - Bancor"))
        self.combobox_HAVE_crypto_currencies.setItemText(98, _translate("MainWindow", "SC - Siacoin"))
        self.lineedit_HAVE_input.setPlaceholderText(_translate("MainWindow", "0.00"))
        self.button_change.setText(_translate("MainWindow", "⇵"))
        self.button_convert.setText(_translate("MainWindow", "Convert"))
        self.groupbox_WANT.setTitle(_translate("MainWindow", "Currency I Want"))
        self.label_WANT_title_currencies.setText(_translate("MainWindow", "Currencies"))
        self.label_WANT_title_crypto_currencies.setText(_translate("MainWindow", "Crypto Currencies"))
        self.combobox_WANT_currencies.setItemText(0, _translate("MainWindow", "USD - US Dollar"))
        self.combobox_WANT_currencies.setItemText(1, _translate("MainWindow", "EUR - Euro"))
        self.combobox_WANT_currencies.setItemText(2, _translate("MainWindow", "JPY - Japanese Yen"))
        self.combobox_WANT_currencies.setItemText(3, _translate("MainWindow", "GBP - British Pound Sterling"))
        self.combobox_WANT_currencies.setItemText(4, _translate("MainWindow", "AUD - Australian Dollar"))
        self.combobox_WANT_currencies.setItemText(5, _translate("MainWindow", "CAD - Canadian Dollar"))
        self.combobox_WANT_currencies.setItemText(6, _translate("MainWindow", "CHF - Swiss Franc"))
        self.combobox_WANT_currencies.setItemText(7, _translate("MainWindow", "CNY - Chinese Yuan"))
        self.combobox_WANT_currencies.setItemText(8, _translate("MainWindow", "SEK - Swedish Krona"))
        self.combobox_WANT_currencies.setItemText(9, _translate("MainWindow", "NZD - New Zealand Dollar"))
        self.combobox_WANT_currencies.setItemText(10, _translate("MainWindow", "AED - Arab Emirates Dirham"))
        self.combobox_WANT_currencies.setItemText(11, _translate("MainWindow", "AFN - Afghan Afghani"))
        self.combobox_WANT_currencies.setItemText(12, _translate("MainWindow", "ALL - Albania Lek"))
        self.combobox_WANT_currencies.setItemText(13, _translate("MainWindow", "AMD - Armenian Dram"))
        self.combobox_WANT_currencies.setItemText(14, _translate("MainWindow", "ANG - Netherlands Antillean Guilder"))
        self.combobox_WANT_currencies.setItemText(15, _translate("MainWindow", "AOA - Angolan Kwanza"))
        self.combobox_WANT_currencies.setItemText(16, _translate("MainWindow", "ARS - Argentine Peso"))
        self.combobox_WANT_currencies.setItemText(17, _translate("MainWindow", "AWG - Aruban Florin"))
        self.combobox_WANT_currencies.setItemText(18, _translate("MainWindow", "AZN - Azerbaijani Manat"))
        self.combobox_WANT_currencies.setItemText(19,
                                                  _translate("MainWindow", "BAM - Bosnia-Herzegovina Convertible Mark"))
        self.combobox_WANT_currencies.setItemText(20, _translate("MainWindow", "BBD - Barbadian Dollar"))
        self.combobox_WANT_currencies.setItemText(21, _translate("MainWindow", "BDT - Bangladeshi Taka"))
        self.combobox_WANT_currencies.setItemText(22, _translate("MainWindow", "BGN - Bulgarian Lev"))
        self.combobox_WANT_currencies.setItemText(23, _translate("MainWindow", "BHD - Bahraini Dinar"))
        self.combobox_WANT_currencies.setItemText(24, _translate("MainWindow", "BIF - Burundian Franc"))
        self.combobox_WANT_currencies.setItemText(25, _translate("MainWindow", "BMD - Bermudan Dollar"))
        self.combobox_WANT_currencies.setItemText(26, _translate("MainWindow", "BND - Brunei Dollar"))
        self.combobox_WANT_currencies.setItemText(27, _translate("MainWindow", "BOB - Bolivian Boliviano"))
        self.combobox_WANT_currencies.setItemText(28, _translate("MainWindow", "BRL - Brazilian Real"))
        self.combobox_WANT_currencies.setItemText(29, _translate("MainWindow", "BSD - Bahamian Dollar"))
        self.combobox_WANT_currencies.setItemText(30, _translate("MainWindow", "BTN - Bhutanese Ngultrum"))
        self.combobox_WANT_currencies.setItemText(31, _translate("MainWindow", "BWP - Botswanan Pula"))
        self.combobox_WANT_currencies.setItemText(32, _translate("MainWindow", "BYR - Belarusian Ruble"))
        self.combobox_WANT_currencies.setItemText(33, _translate("MainWindow", "BZD - Belize Dollar"))
        self.combobox_WANT_currencies.setItemText(34, _translate("MainWindow", "CDF - Congolese Franc"))
        self.combobox_WANT_currencies.setItemText(35, _translate("MainWindow", "CLF - Chilean Unit of Account"))
        self.combobox_WANT_currencies.setItemText(36, _translate("MainWindow", "CLP - Chilean Peso"))
        self.combobox_WANT_currencies.setItemText(37, _translate("MainWindow", "COP - Colombian Peso"))
        self.combobox_WANT_currencies.setItemText(38, _translate("MainWindow", "CRC - Costa Rican Colón"))
        self.combobox_WANT_currencies.setItemText(39, _translate("MainWindow", "CUC - Cuban Convertible Peso"))
        self.combobox_WANT_currencies.setItemText(40, _translate("MainWindow", "CUP - Cuban Peso"))
        self.combobox_WANT_currencies.setItemText(41, _translate("MainWindow", "CVE - Cape Verdean Escudo"))
        self.combobox_WANT_currencies.setItemText(42, _translate("MainWindow", "CZK - Czech Republic Koruna"))
        self.combobox_WANT_currencies.setItemText(43, _translate("MainWindow", "DJF - Djiboutian Franc"))
        self.combobox_WANT_currencies.setItemText(44, _translate("MainWindow", "DKK - Danish Krone"))
        self.combobox_WANT_currencies.setItemText(45, _translate("MainWindow", "DOP - Dominican Peso"))
        self.combobox_WANT_currencies.setItemText(46, _translate("MainWindow", "DZD - Algerian Dinar"))
        self.combobox_WANT_currencies.setItemText(47, _translate("MainWindow", "EGP - Egyptian Pound"))
        self.combobox_WANT_currencies.setItemText(48, _translate("MainWindow", "ERN - Eritrean Nakfa"))
        self.combobox_WANT_currencies.setItemText(49, _translate("MainWindow", "ETB - Ethiopian Birr"))
        self.combobox_WANT_currencies.setItemText(50, _translate("MainWindow", "FJD - Fijian Dollar"))
        self.combobox_WANT_currencies.setItemText(51, _translate("MainWindow", "FKP - Falkland Islands Pound"))
        self.combobox_WANT_currencies.setItemText(52, _translate("MainWindow", "GEL - Georgian Lari"))
        self.combobox_WANT_currencies.setItemText(53, _translate("MainWindow", "GHS - Ghanaian Cedi"))
        self.combobox_WANT_currencies.setItemText(54, _translate("MainWindow", "GIP - Gibraltar Pound"))
        self.combobox_WANT_currencies.setItemText(55, _translate("MainWindow", "GMD - Gambian Dalasi"))
        self.combobox_WANT_currencies.setItemText(56, _translate("MainWindow", "GNF - Guinean Franc"))
        self.combobox_WANT_currencies.setItemText(57, _translate("MainWindow", "GTQ - Guatemalan Quetzal"))
        self.combobox_WANT_currencies.setItemText(58, _translate("MainWindow", "GYD - Guyanaese Dollar"))
        self.combobox_WANT_currencies.setItemText(59, _translate("MainWindow", "HKD - Hong Kong Dollar"))
        self.combobox_WANT_currencies.setItemText(60, _translate("MainWindow", "HNL - Honduran Lempira"))
        self.combobox_WANT_currencies.setItemText(61, _translate("MainWindow", "HRK - Croatian Kuna"))
        self.combobox_WANT_currencies.setItemText(62, _translate("MainWindow", "HTG - Haitian Gourde"))
        self.combobox_WANT_currencies.setItemText(63, _translate("MainWindow", "HUF - Hungarian Forint"))
        self.combobox_WANT_currencies.setItemText(64, _translate("MainWindow", "IDR - Indonesian Rupiah"))
        self.combobox_WANT_currencies.setItemText(65, _translate("MainWindow", "ILS - Israeli New Sheqel"))
        self.combobox_WANT_currencies.setItemText(66, _translate("MainWindow", "IMP - Manx pound"))
        self.combobox_WANT_currencies.setItemText(67, _translate("MainWindow", "INR - Indian Rupee"))
        self.combobox_WANT_currencies.setItemText(68, _translate("MainWindow", "IQD - Iraqi Dinar"))
        self.combobox_WANT_currencies.setItemText(69, _translate("MainWindow", "IRR - Iranian Rial"))
        self.combobox_WANT_currencies.setItemText(70, _translate("MainWindow", "ISK - Icelandic Króna"))
        self.combobox_WANT_currencies.setItemText(71, _translate("MainWindow", "JEP - Jersey Pound"))
        self.combobox_WANT_currencies.setItemText(72, _translate("MainWindow", "JMD - Jamaican Dollar"))
        self.combobox_WANT_currencies.setItemText(73, _translate("MainWindow", "JOD - Jordanian Dinar"))
        self.combobox_WANT_currencies.setItemText(74, _translate("MainWindow", "KES - Kenyan Shilling"))
        self.combobox_WANT_currencies.setItemText(75, _translate("MainWindow", "KGS - Kyrgystani Som"))
        self.combobox_WANT_currencies.setItemText(76, _translate("MainWindow", "KHR - Cambodian Riel"))
        self.combobox_WANT_currencies.setItemText(77, _translate("MainWindow", "KMF - Comorian Franc"))
        self.combobox_WANT_currencies.setItemText(78, _translate("MainWindow", "KPW - North Korean Won"))
        self.combobox_WANT_currencies.setItemText(79, _translate("MainWindow", "KRW - South Korean Won"))
        self.combobox_WANT_currencies.setItemText(80, _translate("MainWindow", "KWD - Kuwaiti Dinar"))
        self.combobox_WANT_currencies.setItemText(81, _translate("MainWindow", "KYD - Cayman Islands Dollar"))
        self.combobox_WANT_currencies.setItemText(82, _translate("MainWindow", "KZT - Kazakhstani Tenge"))
        self.combobox_WANT_currencies.setItemText(83, _translate("MainWindow", "LAK - Laotian Kip"))
        self.combobox_WANT_currencies.setItemText(84, _translate("MainWindow", "LBP - Lebanese Pound"))
        self.combobox_WANT_currencies.setItemText(85, _translate("MainWindow", "LKR - Sri Lankan Rupee"))
        self.combobox_WANT_currencies.setItemText(86, _translate("MainWindow", "LRD - Liberian Dollar"))
        self.combobox_WANT_currencies.setItemText(87, _translate("MainWindow", "LSL - Lesotho Loti"))
        self.combobox_WANT_currencies.setItemText(88, _translate("MainWindow", "LTL - Lithuanian Litas"))
        self.combobox_WANT_currencies.setItemText(89, _translate("MainWindow", "LVL - Latvian Lats"))
        self.combobox_WANT_currencies.setItemText(90, _translate("MainWindow", "LYD - Libyan Dinar"))
        self.combobox_WANT_currencies.setItemText(91, _translate("MainWindow", "MAD - Moroccan Dirham"))
        self.combobox_WANT_currencies.setItemText(92, _translate("MainWindow", "MDL - Moldovan Leu"))
        self.combobox_WANT_currencies.setItemText(93, _translate("MainWindow", "MGA - Malagasy Ariary"))
        self.combobox_WANT_currencies.setItemText(94, _translate("MainWindow", "MKD - Macedonian Denar"))
        self.combobox_WANT_currencies.setItemText(95, _translate("MainWindow", "MMK - Myanma Kyat"))
        self.combobox_WANT_currencies.setItemText(96, _translate("MainWindow", "MNT - Mongolian Tugrik"))
        self.combobox_WANT_currencies.setItemText(97, _translate("MainWindow", "MOP - Macanese Pataca"))
        self.combobox_WANT_currencies.setItemText(98, _translate("MainWindow", "MRO - Mauritanian Ouguiya"))
        self.combobox_WANT_currencies.setItemText(99, _translate("MainWindow", "MUR - Mauritian Rupee"))
        self.combobox_WANT_currencies.setItemText(100, _translate("MainWindow", "MVR - Maldivian Rufiyaa"))
        self.combobox_WANT_currencies.setItemText(101, _translate("MainWindow", "MWK - Malawian Kwacha"))
        self.combobox_WANT_currencies.setItemText(102, _translate("MainWindow", "MXN - Mexican Peso"))
        self.combobox_WANT_currencies.setItemText(103, _translate("MainWindow", "MYR - Malaysian Ringgit"))
        self.combobox_WANT_currencies.setItemText(104, _translate("MainWindow", "MZN - Mozambican Metical"))
        self.combobox_WANT_currencies.setItemText(105, _translate("MainWindow", "NAD - Namibian Dollar"))
        self.combobox_WANT_currencies.setItemText(106, _translate("MainWindow", "NGN - Nigerian Naira"))
        self.combobox_WANT_currencies.setItemText(107, _translate("MainWindow", "NIO - Nicaraguan Córdoba"))
        self.combobox_WANT_currencies.setItemText(108, _translate("MainWindow", "NOK - Norwegian Krone"))
        self.combobox_WANT_currencies.setItemText(109, _translate("MainWindow", "NPR - Nepalese Rupee"))
        self.combobox_WANT_currencies.setItemText(110, _translate("MainWindow", "OMR - Omani Rial"))
        self.combobox_WANT_currencies.setItemText(111, _translate("MainWindow", "PAB - Panamanian Balboa"))
        self.combobox_WANT_currencies.setItemText(112, _translate("MainWindow", "PEN - Peruvian Nuevo Sol"))
        self.combobox_WANT_currencies.setItemText(113, _translate("MainWindow", "PGK - Papua New Guinean Kina"))
        self.combobox_WANT_currencies.setItemText(114, _translate("MainWindow", "PHP - Philippine Peso"))
        self.combobox_WANT_currencies.setItemText(115, _translate("MainWindow", "PKR - Pakistani Rupee"))
        self.combobox_WANT_currencies.setItemText(116, _translate("MainWindow", "PLN - Polish Zloty"))
        self.combobox_WANT_currencies.setItemText(117, _translate("MainWindow", "PYG - Paraguayan Guarani"))
        self.combobox_WANT_currencies.setItemText(118, _translate("MainWindow", "QAR - Qatari Rial"))
        self.combobox_WANT_currencies.setItemText(119, _translate("MainWindow", "RON - Romanian Leu"))
        self.combobox_WANT_currencies.setItemText(120, _translate("MainWindow", "RSD - Serbian Dinar"))
        self.combobox_WANT_currencies.setItemText(121, _translate("MainWindow", "RUB - Russian Ruble"))
        self.combobox_WANT_currencies.setItemText(122, _translate("MainWindow", "RWF - Rwandan Franc"))
        self.combobox_WANT_currencies.setItemText(123, _translate("MainWindow", "SAR - Saudi Riyal"))
        self.combobox_WANT_currencies.setItemText(124, _translate("MainWindow", "SBD - Solomon Islands Dollar"))
        self.combobox_WANT_currencies.setItemText(125, _translate("MainWindow", "SCR - Seychellois Rupee"))
        self.combobox_WANT_currencies.setItemText(126, _translate("MainWindow", "SDG - Sudanese Pound"))
        self.combobox_WANT_currencies.setItemText(127, _translate("MainWindow", "SGD - Singapore Dollar"))
        self.combobox_WANT_currencies.setItemText(128, _translate("MainWindow", "SHP - Saint Helena Pound"))
        self.combobox_WANT_currencies.setItemText(129, _translate("MainWindow", "SLL - Sierra Leonean Leone"))
        self.combobox_WANT_currencies.setItemText(130, _translate("MainWindow", "SOS - Somali Shilling"))
        self.combobox_WANT_currencies.setItemText(131, _translate("MainWindow", "SRD - Surinamese Dollar"))
        self.combobox_WANT_currencies.setItemText(132, _translate("MainWindow", "STD - São Tomé and Príncipe Dobra"))
        self.combobox_WANT_currencies.setItemText(133, _translate("MainWindow", "SVC - Salvadoran Colón"))
        self.combobox_WANT_currencies.setItemText(134, _translate("MainWindow", "SYP - Syrian Pound"))
        self.combobox_WANT_currencies.setItemText(135, _translate("MainWindow", "SZL - Swazi Lilangeni"))
        self.combobox_WANT_currencies.setItemText(136, _translate("MainWindow", "THB - Thai Baht"))
        self.combobox_WANT_currencies.setItemText(137, _translate("MainWindow", "TJS - Tajikistani Somoni"))
        self.combobox_WANT_currencies.setItemText(138, _translate("MainWindow", "TMT - Turkmenistani Manat"))
        self.combobox_WANT_currencies.setItemText(139, _translate("MainWindow", "TND - Tunisian Dinar"))
        self.combobox_WANT_currencies.setItemText(140, _translate("MainWindow", "TOP - Tongan Paʻanga"))
        self.combobox_WANT_currencies.setItemText(141, _translate("MainWindow", "TRY - Turkish Lira"))
        self.combobox_WANT_currencies.setItemText(142, _translate("MainWindow", "TTD - Trinidad and Tobago Dollar"))
        self.combobox_WANT_currencies.setItemText(143, _translate("MainWindow", "TWD - New Taiwan Dollar"))
        self.combobox_WANT_currencies.setItemText(144, _translate("MainWindow", "TZS - Tanzanian Shilling"))
        self.combobox_WANT_currencies.setItemText(145, _translate("MainWindow", "UAH - Ukrainian Hryvnia"))
        self.combobox_WANT_currencies.setItemText(146, _translate("MainWindow", "UGX - Ugandan Shilling"))
        self.combobox_WANT_currencies.setItemText(147, _translate("MainWindow", "UYU - Uruguayan Peso"))
        self.combobox_WANT_currencies.setItemText(148, _translate("MainWindow", "UZS - Uzbekistan Som"))
        self.combobox_WANT_currencies.setItemText(149, _translate("MainWindow", "VEF - Venezuelan Bolívar Fuerte"))
        self.combobox_WANT_currencies.setItemText(150, _translate("MainWindow", "VND - Vietnamese Dong"))
        self.combobox_WANT_currencies.setItemText(151, _translate("MainWindow", "VUV - Vanuatu Vatu"))
        self.combobox_WANT_currencies.setItemText(152, _translate("MainWindow", "WST - Samoan Tala"))
        self.combobox_WANT_currencies.setItemText(153, _translate("MainWindow", "XAF - CFA Franc BEAC"))
        self.combobox_WANT_currencies.setItemText(154, _translate("MainWindow", "XCD - East Caribbean Dollar"))
        self.combobox_WANT_currencies.setItemText(155, _translate("MainWindow", "XOF - CFA Franc BCEAO"))
        self.combobox_WANT_currencies.setItemText(156, _translate("MainWindow", "XPF - CFP Franc"))
        self.combobox_WANT_currencies.setItemText(157, _translate("MainWindow", "YER - Yemeni Rial"))
        self.combobox_WANT_currencies.setItemText(158, _translate("MainWindow", "ZAR - South African Rand"))
        self.combobox_WANT_currencies.setItemText(159, _translate("MainWindow", "ZMW - Zambian Kwacha"))
        self.combobox_WANT_currencies.setItemText(160, _translate("MainWindow", "ZWL - Zimbabwean Dollar"))
        self.combobox_WANT_crypto_currencies.setItemText(0, _translate("MainWindow", "BTC - Bitcoin"))
        self.combobox_WANT_crypto_currencies.setItemText(1, _translate("MainWindow", "ETH - Ethereum"))
        self.combobox_WANT_crypto_currencies.setItemText(2, _translate("MainWindow", "ADA - Cardano"))
        self.combobox_WANT_crypto_currencies.setItemText(3, _translate("MainWindow", "BNB - Binance Coin"))
        self.combobox_WANT_crypto_currencies.setItemText(4, _translate("MainWindow", "USDT - TETHER"))
        self.combobox_WANT_crypto_currencies.setItemText(5, _translate("MainWindow", "SOL - Solona"))
        self.combobox_WANT_crypto_currencies.setItemText(6, _translate("MainWindow", "XRP - Xrp"))
        self.combobox_WANT_crypto_currencies.setItemText(7, _translate("MainWindow", "DOGE - Dogecoin"))
        self.combobox_WANT_crypto_currencies.setItemText(8, _translate("MainWindow", "DOT - Polkadot"))
        self.combobox_WANT_crypto_currencies.setItemText(9, _translate("MainWindow", "USDC - USD Coin"))
        self.combobox_WANT_crypto_currencies.setItemText(10, _translate("MainWindow", "LUNA - Terra"))
        self.combobox_WANT_crypto_currencies.setItemText(11, _translate("MainWindow", "UNI - Uniswap"))
        self.combobox_WANT_crypto_currencies.setItemText(12, _translate("MainWindow", "LINK - Chainlink"))
        self.combobox_WANT_crypto_currencies.setItemText(13, _translate("MainWindow", "BUSD - Binance USD"))
        self.combobox_WANT_crypto_currencies.setItemText(14, _translate("MainWindow", "BCH - Bitcoin Cash"))
        self.combobox_WANT_crypto_currencies.setItemText(15, _translate("MainWindow", "LTC - Litecoin"))
        self.combobox_WANT_crypto_currencies.setItemText(16, _translate("MainWindow", "ALGO - Algorand"))
        self.combobox_WANT_crypto_currencies.setItemText(17, _translate("MainWindow", "AVAX - Avalanche"))
        self.combobox_WANT_crypto_currencies.setItemText(18, _translate("MainWindow", "ICP - Internet Computer"))
        self.combobox_WANT_crypto_currencies.setItemText(19, _translate("MainWindow", "WBTC - Wrapped Bitcoin"))
        self.combobox_WANT_crypto_currencies.setItemText(20, _translate("MainWindow", "MATIC - Polygon"))
        self.combobox_WANT_crypto_currencies.setItemText(21, _translate("MainWindow", "FTT - FTX Token"))
        self.combobox_WANT_crypto_currencies.setItemText(22, _translate("MainWindow", "FIL - Filecoin"))
        self.combobox_WANT_crypto_currencies.setItemText(23, _translate("MainWindow", "XLM - Stellar"))
        self.combobox_WANT_crypto_currencies.setItemText(24, _translate("MainWindow", "VET - VeChain"))
        self.combobox_WANT_crypto_currencies.setItemText(25, _translate("MainWindow", "ETC - Ethereum Classic"))
        self.combobox_WANT_crypto_currencies.setItemText(26, _translate("MainWindow", "THETA - Theta"))
        self.combobox_WANT_crypto_currencies.setItemText(27, _translate("MainWindow", "DAI - Dai"))
        self.combobox_WANT_crypto_currencies.setItemText(28, _translate("MainWindow", "TRX - Tron"))
        self.combobox_WANT_crypto_currencies.setItemText(29, _translate("MainWindow", "ATOM - Cosmos"))
        self.combobox_WANT_crypto_currencies.setItemText(30, _translate("MainWindow", "XTZ - Tezos"))
        self.combobox_WANT_crypto_currencies.setItemText(31, _translate("MainWindow", "XMR - Monero"))
        self.combobox_WANT_crypto_currencies.setItemText(32, _translate("MainWindow", "MIOTA - IOTA"))
        self.combobox_WANT_crypto_currencies.setItemText(33, _translate("MainWindow", "EOS - EOS"))
        self.combobox_WANT_crypto_currencies.setItemText(34, _translate("MainWindow", "XEC - ECash"))
        self.combobox_WANT_crypto_currencies.setItemText(35, _translate("MainWindow", "CRO - Crypto.com Coin"))
        self.combobox_WANT_crypto_currencies.setItemText(36, _translate("MainWindow", "CAKE - PancakeSwap"))
        self.combobox_WANT_crypto_currencies.setItemText(37, _translate("MainWindow", "EGLD - Elrond"))
        self.combobox_WANT_crypto_currencies.setItemText(38, _translate("MainWindow", "AAVE - Aave"))
        self.combobox_WANT_crypto_currencies.setItemText(39, _translate("MainWindow", "NEAR - NEAR Protocol"))
        self.combobox_WANT_crypto_currencies.setItemText(40, _translate("MainWindow", "AXS - Axie Infinity"))
        self.combobox_WANT_crypto_currencies.setItemText(41, _translate("MainWindow", "FTM - Fantom"))
        self.combobox_WANT_crypto_currencies.setItemText(42, _translate("MainWindow", "GRT - The Graph"))
        self.combobox_WANT_crypto_currencies.setItemText(43, _translate("MainWindow", "QNT - Quant"))
        self.combobox_WANT_crypto_currencies.setItemText(44, _translate("MainWindow", "BTCB - Bitcoin BEP2"))
        self.combobox_WANT_crypto_currencies.setItemText(45, _translate("MainWindow", "NEO - Neo"))
        self.combobox_WANT_crypto_currencies.setItemText(46, _translate("MainWindow", "KLAY - Klaytn"))
        self.combobox_WANT_crypto_currencies.setItemText(47, _translate("MainWindow", "KSM - Kusama"))
        self.combobox_WANT_crypto_currencies.setItemText(48, _translate("MainWindow", "WAVES - Waves"))
        self.combobox_WANT_crypto_currencies.setItemText(49, _translate("MainWindow", "HBAR - Hedera Hashgraph"))
        self.combobox_WANT_crypto_currencies.setItemText(50, _translate("MainWindow", "BSV - Bitcoin SV"))
        self.combobox_WANT_crypto_currencies.setItemText(51, _translate("MainWindow", "LEO - UNUS SED LEO"))
        self.combobox_WANT_crypto_currencies.setItemText(52, _translate("MainWindow", "MKR - Maker"))
        self.combobox_WANT_crypto_currencies.setItemText(53, _translate("MainWindow", "SHIB - SHIBA INU"))
        self.combobox_WANT_crypto_currencies.setItemText(54, _translate("MainWindow", "BTT - BitTorrent"))
        self.combobox_WANT_crypto_currencies.setItemText(55, _translate("MainWindow", "UST - TerraUSD"))
        self.combobox_WANT_crypto_currencies.setItemText(56, _translate("MainWindow", "HT - Huobi Token"))
        self.combobox_WANT_crypto_currencies.setItemText(57, _translate("MainWindow", "AMP - Amp"))
        self.combobox_WANT_crypto_currencies.setItemText(58, _translate("MainWindow", "COMP - Compound"))
        self.combobox_WANT_crypto_currencies.setItemText(59, _translate("MainWindow", "AR - Arweave"))
        self.combobox_WANT_crypto_currencies.setItemText(60, _translate("MainWindow", "DASH - Dash"))
        self.combobox_WANT_crypto_currencies.setItemText(61, _translate("MainWindow", "REV - Revain"))
        self.combobox_WANT_crypto_currencies.setItemText(62, _translate("MainWindow", "CHZ - Chiliz"))
        self.combobox_WANT_crypto_currencies.setItemText(63, _translate("MainWindow", "DCR - Decred"))
        self.combobox_WANT_crypto_currencies.setItemText(64, _translate("MainWindow", "RUNE - THORChain"))
        self.combobox_WANT_crypto_currencies.setItemText(65, _translate("MainWindow", "HNT - Helium"))
        self.combobox_WANT_crypto_currencies.setItemText(66, _translate("MainWindow", "ONE - Harmony"))
        self.combobox_WANT_crypto_currencies.setItemText(67, _translate("MainWindow", "STX - Stacks"))
        self.combobox_WANT_crypto_currencies.setItemText(68, _translate("MainWindow", "HOT - Holo"))
        self.combobox_WANT_crypto_currencies.setItemText(69, _translate("MainWindow", "ZEC - Zcash"))
        self.combobox_WANT_crypto_currencies.setItemText(70, _translate("MainWindow", "TFUEL - Theta Fuel"))
        self.combobox_WANT_crypto_currencies.setItemText(71, _translate("MainWindow", "XEM - NEM"))
        self.combobox_WANT_crypto_currencies.setItemText(72, _translate("MainWindow", "CELO - Celo"))
        self.combobox_WANT_crypto_currencies.setItemText(73, _translate("MainWindow", "XDC - XinFin"))
        self.combobox_WANT_crypto_currencies.setItemText(74, _translate("MainWindow", "MANA - Decentraland"))
        self.combobox_WANT_crypto_currencies.setItemText(75, _translate("MainWindow", "ENJ - Enjin Coin"))
        self.combobox_WANT_crypto_currencies.setItemText(76, _translate("MainWindow", "TUSD - TrueUSD"))
        self.combobox_WANT_crypto_currencies.setItemText(77, _translate("MainWindow", "IOST - IOST"))
        self.combobox_WANT_crypto_currencies.setItemText(78, _translate("MainWindow", "CEL - Celsius"))
        self.combobox_WANT_crypto_currencies.setItemText(79, _translate("MainWindow", "SUSHI - Sushiswap"))
        self.combobox_WANT_crypto_currencies.setItemText(80, _translate("MainWindow", "ZIL - Zilliqa"))
        self.combobox_WANT_crypto_currencies.setItemText(81, _translate("MainWindow", "QTUM - Qtum"))
        self.combobox_WANT_crypto_currencies.setItemText(82, _translate("MainWindow", "SNX - Synthetix"))
        self.combobox_WANT_crypto_currencies.setItemText(83, _translate("MainWindow", "ICX - ICON"))
        self.combobox_WANT_crypto_currencies.setItemText(84, _translate("MainWindow", "YFI - Yearn.finance"))
        self.combobox_WANT_crypto_currencies.setItemText(85, _translate("MainWindow", "MDX - Mdex"))
        self.combobox_WANT_crypto_currencies.setItemText(86, _translate("MainWindow", "MINA - Mina"))
        self.combobox_WANT_crypto_currencies.setItemText(87, _translate("MainWindow", "OMG - OMG Network"))
        self.combobox_WANT_crypto_currencies.setItemText(88, _translate("MainWindow", "BTG - Bitcoin Gold"))
        self.combobox_WANT_crypto_currencies.setItemText(89, _translate("MainWindow", "FLOW - Flow"))
        self.combobox_WANT_crypto_currencies.setItemText(90, _translate("MainWindow", "BAT - Basic Attention Token"))
        self.combobox_WANT_crypto_currencies.setItemText(91, _translate("MainWindow", "RVN - Ravencoin"))
        self.combobox_WANT_crypto_currencies.setItemText(92, _translate("MainWindow", "OKB - OKB"))
        self.combobox_WANT_crypto_currencies.setItemText(93, _translate("MainWindow", "TEL - Telcoin"))
        self.combobox_WANT_crypto_currencies.setItemText(94, _translate("MainWindow", "AUDIO - Audius"))
        self.combobox_WANT_crypto_currencies.setItemText(95, _translate("MainWindow", "PERP - Curve DAO Token"))
        self.combobox_WANT_crypto_currencies.setItemText(96, _translate("MainWindow", "ZEN - Horizen"))
        self.combobox_WANT_crypto_currencies.setItemText(97, _translate("MainWindow", "BNT - Bancor"))
        self.combobox_WANT_crypto_currencies.setItemText(98, _translate("MainWindow", "SC - Siacoin"))
        self.lbl_copyright.setText(_translate("MainWindow",
                                              "<html><head/><body><p><span style=\" font-size:7pt; color:#000000;\">© Designed and Developed by </span><a href=\"https://github.com/mehmetguduk\"><span style=\" font-size:7pt; text-decoration: underline; color:#0000ff;\">Mehmet Güdük</span></a></p></body></html>"))


import images
