# © Designed and Developed by Mehmet Güdük.
# © Licensed with GPL-3.0 License, Author is Mehmet Güdük.


# The visual and design part of the application is here.


from PyQt5 import QtCore, QtGui, QtWidgets

import currencies


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(500, 400))
        MainWindow.setMaximumSize(QtCore.QSize(500, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/images/logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 461, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupbox_HAVE = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupbox_HAVE.setObjectName("groupbox_HAVE")
        self.label_HAVE_title_currencies = QtWidgets.QLabel(self.groupbox_HAVE)
        self.label_HAVE_title_currencies.setGeometry(QtCore.QRect(10, 30, 221, 21))
        self.label_HAVE_title_currencies.setFrameShape(QtWidgets.QFrame.Box)
        self.label_HAVE_title_currencies.setAlignment(QtCore.Qt.AlignCenter)
        self.label_HAVE_title_currencies.setObjectName("label_HAVE_title_currencies")
        self.label_HAVE_selected_currency = QtWidgets.QLabel(self.groupbox_HAVE)
        self.label_HAVE_selected_currency.setGeometry(QtCore.QRect(10, 90, 441, 21))
        self.label_HAVE_selected_currency.setFrameShape(QtWidgets.QFrame.Box)
        self.label_HAVE_selected_currency.setText("")
        self.label_HAVE_selected_currency.setAlignment(QtCore.Qt.AlignCenter)
        self.label_HAVE_selected_currency.setObjectName("label_HAVE_selected_currency")
        self.combobox_HAVE_currencies = QtWidgets.QComboBox(self.groupbox_HAVE)
        self.combobox_HAVE_currencies.setGeometry(QtCore.QRect(10, 50, 221, 22))
        self.combobox_HAVE_currencies.setObjectName("combobox_HAVE_currencies")
        self.currency_icons = []

        def add_currency_icon(abbreviation: str):
            Icon = QtGui.QIcon()
            Icon.addPixmap(
                QtGui.QPixmap(f":/currencies/images/Currencies/{abbreviation.lower()}.png"),
                QtGui.QIcon.Normal,
                QtGui.QIcon.Off
            )
            self.currency_icons.append(Icon)
            self.combobox_HAVE_currencies.addItem(Icon, "")

        for currency in currencies.currencies:
            add_currency_icon(abbreviation=currency['abbreviation'])
        self.label_HAVE_title_crypto_currencies = QtWidgets.QLabel(self.groupbox_HAVE)
        self.label_HAVE_title_crypto_currencies.setGeometry(QtCore.QRect(230, 30, 221, 21))
        self.label_HAVE_title_crypto_currencies.setFrameShape(QtWidgets.QFrame.Box)
        self.label_HAVE_title_crypto_currencies.setAlignment(QtCore.Qt.AlignCenter)
        self.label_HAVE_title_crypto_currencies.setObjectName("label_HAVE_title_crypto_currencies")
        self.combobox_HAVE_crypto_currencies = QtWidgets.QComboBox(self.groupbox_HAVE)
        self.combobox_HAVE_crypto_currencies.setGeometry(QtCore.QRect(230, 50, 221, 22))
        self.combobox_HAVE_crypto_currencies.setObjectName("combobox_HAVE_crypto_currencies")
        self.crypto_currency_icons = []

        def add_crypto_currency_icon(abbreviation: str):
            Icon = QtGui.QIcon()
            Icon.addPixmap(QtGui.QPixmap(f":/crypto currencies/images/Crypto Currencies/{abbreviation.lower()}.png"),
                           QtGui.QIcon.Normal, QtGui.QIcon.Off)
            self.crypto_currency_icons.append(Icon)
            self.combobox_HAVE_crypto_currencies.addItem(Icon, "")
        for crypto_currency in currencies.crypto_currencies:
            add_crypto_currency_icon(abbreviation=crypto_currency['abbreviation'])
        self.lineedit_HAVE_input = QtWidgets.QLineEdit(self.groupbox_HAVE)
        self.lineedit_HAVE_input.setGeometry(QtCore.QRect(10, 110, 441, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineedit_HAVE_input.setFont(font)
        self.lineedit_HAVE_input.setInputMethodHints(QtCore.Qt.ImhDigitsOnly | QtCore.Qt.ImhFormattedNumbersOnly)
        self.lineedit_HAVE_input.setInputMask("")
        self.lineedit_HAVE_input.setText("")
        self.lineedit_HAVE_input.setMaxLength(36)
        self.lineedit_HAVE_input.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineedit_HAVE_input.setAlignment(QtCore.Qt.AlignCenter)
        self.lineedit_HAVE_input.setClearButtonEnabled(False)
        self.lineedit_HAVE_input.setObjectName("lineedit_HAVE_input")
        self.verticalLayout.addWidget(self.groupbox_HAVE)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.button_change = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_change.setObjectName("button_change")
        self.horizontalLayout.addWidget(self.button_change)
        self.button_convert = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_convert.setObjectName("button_convert")
        self.horizontalLayout.addWidget(self.button_convert)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupbox_WANT = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupbox_WANT.setObjectName("groupbox_WANT")
        self.label_WANT_title_currencies = QtWidgets.QLabel(self.groupbox_WANT)
        self.label_WANT_title_currencies.setGeometry(QtCore.QRect(10, 30, 221, 21))
        self.label_WANT_title_currencies.setFrameShape(QtWidgets.QFrame.Box)
        self.label_WANT_title_currencies.setAlignment(QtCore.Qt.AlignCenter)
        self.label_WANT_title_currencies.setObjectName("label_WANT_title_currencies")
        self.label_WANT_title_crypto_currencies = QtWidgets.QLabel(self.groupbox_WANT)
        self.label_WANT_title_crypto_currencies.setGeometry(QtCore.QRect(230, 30, 221, 21))
        self.label_WANT_title_crypto_currencies.setFrameShape(QtWidgets.QFrame.Box)
        self.label_WANT_title_crypto_currencies.setAlignment(QtCore.Qt.AlignCenter)
        self.label_WANT_title_crypto_currencies.setObjectName("label_WANT_title_crypto_currencies")
        self.combobox_WANT_currencies = QtWidgets.QComboBox(self.groupbox_WANT)
        self.combobox_WANT_currencies.setGeometry(QtCore.QRect(10, 50, 221, 22))
        self.combobox_WANT_currencies.setObjectName("combobox_WANT_currencies")
        for icon_ in self.currency_icons:
            self.combobox_WANT_currencies.addItem(icon_, "")
        self.combobox_WANT_crypto_currencies = QtWidgets.QComboBox(self.groupbox_WANT)
        self.combobox_WANT_crypto_currencies.setGeometry(QtCore.QRect(230, 50, 221, 22))
        self.combobox_WANT_crypto_currencies.setObjectName("combobox_WANT_crypto_currencies")
        for icon_ in self.crypto_currency_icons:
            self.combobox_WANT_crypto_currencies.addItem(icon_, "")
        self.label_WANT_selected_currency = QtWidgets.QLabel(self.groupbox_WANT)
        self.label_WANT_selected_currency.setGeometry(QtCore.QRect(10, 90, 441, 21))
        self.label_WANT_selected_currency.setFrameShape(QtWidgets.QFrame.Box)
        self.label_WANT_selected_currency.setText("")
        self.label_WANT_selected_currency.setAlignment(QtCore.Qt.AlignCenter)
        self.label_WANT_selected_currency.setObjectName("label_WANT_selected_currency")
        self.lineedit_WANT_output = QtWidgets.QLineEdit(self.groupbox_WANT)
        self.lineedit_WANT_output.setGeometry(QtCore.QRect(10, 110, 441, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineedit_WANT_output.setFont(font)
        self.lineedit_WANT_output.setInputMethodHints(QtCore.Qt.ImhDigitsOnly | QtCore.Qt.ImhFormattedNumbersOnly)
        self.lineedit_WANT_output.setInputMask("")
        self.lineedit_WANT_output.setText("")
        self.lineedit_WANT_output.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineedit_WANT_output.setAlignment(QtCore.Qt.AlignCenter)
        self.lineedit_WANT_output.setReadOnly(True)
        self.lineedit_WANT_output.setClearButtonEnabled(False)
        self.lineedit_WANT_output.setObjectName("lineedit_WANT_output")
        self.verticalLayout.addWidget(self.groupbox_WANT)
        self.verticalLayout.setStretch(0, 45)
        self.verticalLayout.setStretch(1, 10)
        self.verticalLayout.setStretch(2, 45)
        self.lbl_copyright = QtWidgets.QLabel(self.centralwidget)
        self.lbl_copyright.setGeometry(QtCore.QRect(0, 380, 501, 20))
        self.lbl_copyright.setStyleSheet("color: rgb(0, 0, 0);")
        self.lbl_copyright.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_copyright.setObjectName("lbl_copyright")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.combobox_HAVE_currencies.setCurrentIndex(-1)
        self.combobox_HAVE_crypto_currencies.setCurrentIndex(-1)
        self.combobox_WANT_currencies.setCurrentIndex(-1)
        self.combobox_WANT_crypto_currencies.setCurrentIndex(-1)
        self.combobox_HAVE_currencies.currentIndexChanged['QString'].connect(self.label_HAVE_selected_currency.setText)
        self.combobox_HAVE_crypto_currencies.currentIndexChanged['QString'].connect(
            self.label_HAVE_selected_currency.setText)
        self.combobox_WANT_currencies.currentIndexChanged['QString'].connect(self.label_WANT_selected_currency.setText)
        self.combobox_WANT_crypto_currencies.currentIndexChanged['QString'].connect(
            self.label_WANT_selected_currency.setText)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Currency Converter"))
        self.groupbox_HAVE.setTitle(_translate("MainWindow", "Currency I Have"))
        self.label_HAVE_title_currencies.setText(_translate("MainWindow", "Currencies"))
        self.combobox_HAVE_currencies.setItemText(0, _translate("MainWindow", "USD - US Dollar"))
        self.combobox_HAVE_currencies.setItemText(1, _translate("MainWindow", "EUR - Euro"))
        self.combobox_HAVE_currencies.setItemText(2, _translate("MainWindow", "JPY - Japanese Yen"))
        self.combobox_HAVE_currencies.setItemText(3, _translate("MainWindow", "GBP - British Pound Sterling"))
        self.combobox_HAVE_currencies.setItemText(4, _translate("MainWindow", "AUD - Australian Dollar"))
        self.combobox_HAVE_currencies.setItemText(5, _translate("MainWindow", "CAD - Canadian Dollar"))
        self.combobox_HAVE_currencies.setItemText(6, _translate("MainWindow", "CHF - Swiss Franc"))
        self.combobox_HAVE_currencies.setItemText(7, _translate("MainWindow", "CNY - Chinese Yuan"))
        self.combobox_HAVE_currencies.setItemText(8, _translate("MainWindow", "SEK - Swedish Krona"))
        self.combobox_HAVE_currencies.setItemText(9, _translate("MainWindow", "NZD - New Zealand Dollar"))
        self.combobox_HAVE_currencies.setItemText(10, _translate("MainWindow", "AED - Arab Emirates Dirham"))
        self.combobox_HAVE_currencies.setItemText(11, _translate("MainWindow", "AFN - Afghan Afghani"))
        self.combobox_HAVE_currencies.setItemText(12, _translate("MainWindow", "ALL - Albania Lek"))
        self.combobox_HAVE_currencies.setItemText(13, _translate("MainWindow", "AMD - Armenian Dram"))
        self.combobox_HAVE_currencies.setItemText(14, _translate("MainWindow", "ANG - Netherlands Antillean Guilder"))
        self.combobox_HAVE_currencies.setItemText(15, _translate("MainWindow", "AOA - Angolan Kwanza"))
        self.combobox_HAVE_currencies.setItemText(16, _translate("MainWindow", "ARS - Argentine Peso"))
        self.combobox_HAVE_currencies.setItemText(17, _translate("MainWindow", "AWG - Aruban Florin"))
        self.combobox_HAVE_currencies.setItemText(18, _translate("MainWindow", "AZN - Azerbaijani Manat"))
        self.combobox_HAVE_currencies.setItemText(19,
                                                  _translate("MainWindow", "BAM - Bosnia-Herzegovina Convertible Mark"))
        self.combobox_HAVE_currencies.setItemText(20, _translate("MainWindow", "BBD - Barbadian Dollar"))
        self.combobox_HAVE_currencies.setItemText(21, _translate("MainWindow", "BDT - Bangladeshi Taka"))
        self.combobox_HAVE_currencies.setItemText(22, _translate("MainWindow", "BGN - Bulgarian Lev"))
        self.combobox_HAVE_currencies.setItemText(23, _translate("MainWindow", "BHD - Bahraini Dinar"))
        self.combobox_HAVE_currencies.setItemText(24, _translate("MainWindow", "BIF - Burundian Franc"))
        self.combobox_HAVE_currencies.setItemText(25, _translate("MainWindow", "BMD - Bermudan Dollar"))
        self.combobox_HAVE_currencies.setItemText(26, _translate("MainWindow", "BND - Brunei Dollar"))
        self.combobox_HAVE_currencies.setItemText(27, _translate("MainWindow", "BOB - Bolivian Boliviano"))
        self.combobox_HAVE_currencies.setItemText(28, _translate("MainWindow", "BRL - Brazilian Real"))
        self.combobox_HAVE_currencies.setItemText(29, _translate("MainWindow", "BSD - Bahamian Dollar"))
        self.combobox_HAVE_currencies.setItemText(30, _translate("MainWindow", "BTN - Bhutanese Ngultrum"))
        self.combobox_HAVE_currencies.setItemText(31, _translate("MainWindow", "BWP - Botswanan Pula"))
        self.combobox_HAVE_currencies.setItemText(32, _translate("MainWindow", "BYR - Belarusian Ruble"))
        self.combobox_HAVE_currencies.setItemText(33, _translate("MainWindow", "BZD - Belize Dollar"))
        self.combobox_HAVE_currencies.setItemText(34, _translate("MainWindow", "CDF - Congolese Franc"))
        self.combobox_HAVE_currencies.setItemText(35, _translate("MainWindow", "CLF - Chilean Unit of Account"))
        self.combobox_HAVE_currencies.setItemText(36, _translate("MainWindow", "CLP - Chilean Peso"))
        self.combobox_HAVE_currencies.setItemText(37, _translate("MainWindow", "COP - Colombian Peso"))
        self.combobox_HAVE_currencies.setItemText(38, _translate("MainWindow", "CRC - Costa Rican Colón"))
        self.combobox_HAVE_currencies.setItemText(39, _translate("MainWindow", "CUC - Cuban Convertible Peso"))
        self.combobox_HAVE_currencies.setItemText(40, _translate("MainWindow", "CUP - Cuban Peso"))
        self.combobox_HAVE_currencies.setItemText(41, _translate("MainWindow", "CVE - Cape Verdean Escudo"))
        self.combobox_HAVE_currencies.setItemText(42, _translate("MainWindow", "CZK - Czech Republic Koruna"))
        self.combobox_HAVE_currencies.setItemText(43, _translate("MainWindow", "DJF - Djiboutian Franc"))
        self.combobox_HAVE_currencies.setItemText(44, _translate("MainWindow", "DKK - Danish Krone"))
        self.combobox_HAVE_currencies.setItemText(45, _translate("MainWindow", "DOP - Dominican Peso"))
        self.combobox_HAVE_currencies.setItemText(46, _translate("MainWindow", "DZD - Algerian Dinar"))
        self.combobox_HAVE_currencies.setItemText(47, _translate("MainWindow", "EGP - Egyptian Pound"))
        self.combobox_HAVE_currencies.setItemText(48, _translate("MainWindow", "ERN - Eritrean Nakfa"))
        self.combobox_HAVE_currencies.setItemText(49, _translate("MainWindow", "ETB - Ethiopian Birr"))
        self.combobox_HAVE_currencies.setItemText(50, _translate("MainWindow", "FJD - Fijian Dollar"))
        self.combobox_HAVE_currencies.setItemText(51, _translate("MainWindow", "FKP - Falkland Islands Pound"))
        self.combobox_HAVE_currencies.setItemText(52, _translate("MainWindow", "GEL - Georgian Lari"))
        self.combobox_HAVE_currencies.setItemText(53, _translate("MainWindow", "GHS - Ghanaian Cedi"))
        self.combobox_HAVE_currencies.setItemText(54, _translate("MainWindow", "GIP - Gibraltar Pound"))
        self.combobox_HAVE_currencies.setItemText(55, _translate("MainWindow", "GMD - Gambian Dalasi"))
        self.combobox_HAVE_currencies.setItemText(56, _translate("MainWindow", "GNF - Guinean Franc"))
        self.combobox_HAVE_currencies.setItemText(57, _translate("MainWindow", "GTQ - Guatemalan Quetzal"))
        self.combobox_HAVE_currencies.setItemText(58, _translate("MainWindow", "GYD - Guyanaese Dollar"))
        self.combobox_HAVE_currencies.setItemText(59, _translate("MainWindow", "HKD - Hong Kong Dollar"))
        self.combobox_HAVE_currencies.setItemText(60, _translate("MainWindow", "HNL - Honduran Lempira"))
        self.combobox_HAVE_currencies.setItemText(61, _translate("MainWindow", "HRK - Croatian Kuna"))
        self.combobox_HAVE_currencies.setItemText(62, _translate("MainWindow", "HTG - Haitian Gourde"))
        self.combobox_HAVE_currencies.setItemText(63, _translate("MainWindow", "HUF - Hungarian Forint"))
        self.combobox_HAVE_currencies.setItemText(64, _translate("MainWindow", "IDR - Indonesian Rupiah"))
        self.combobox_HAVE_currencies.setItemText(65, _translate("MainWindow", "ILS - Israeli New Sheqel"))
        self.combobox_HAVE_currencies.setItemText(66, _translate("MainWindow", "IMP - Manx pound"))
        self.combobox_HAVE_currencies.setItemText(67, _translate("MainWindow", "INR - Indian Rupee"))
        self.combobox_HAVE_currencies.setItemText(68, _translate("MainWindow", "IQD - Iraqi Dinar"))
        self.combobox_HAVE_currencies.setItemText(69, _translate("MainWindow", "IRR - Iranian Rial"))
        self.combobox_HAVE_currencies.setItemText(70, _translate("MainWindow", "ISK - Icelandic Króna"))
        self.combobox_HAVE_currencies.setItemText(71, _translate("MainWindow", "JEP - Jersey Pound"))
        self.combobox_HAVE_currencies.setItemText(72, _translate("MainWindow", "JMD - Jamaican Dollar"))
        self.combobox_HAVE_currencies.setItemText(73, _translate("MainWindow", "JOD - Jordanian Dinar"))
        self.combobox_HAVE_currencies.setItemText(74, _translate("MainWindow", "KES - Kenyan Shilling"))
        self.combobox_HAVE_currencies.setItemText(75, _translate("MainWindow", "KGS - Kyrgystani Som"))
        self.combobox_HAVE_currencies.setItemText(76, _translate("MainWindow", "KHR - Cambodian Riel"))
        self.combobox_HAVE_currencies.setItemText(77, _translate("MainWindow", "KMF - Comorian Franc"))
        self.combobox_HAVE_currencies.setItemText(78, _translate("MainWindow", "KPW - North Korean Won"))
        self.combobox_HAVE_currencies.setItemText(79, _translate("MainWindow", "KRW - South Korean Won"))
        self.combobox_HAVE_currencies.setItemText(80, _translate("MainWindow", "KWD - Kuwaiti Dinar"))
        self.combobox_HAVE_currencies.setItemText(81, _translate("MainWindow", "KYD - Cayman Islands Dollar"))
        self.combobox_HAVE_currencies.setItemText(82, _translate("MainWindow", "KZT - Kazakhstani Tenge"))
        self.combobox_HAVE_currencies.setItemText(83, _translate("MainWindow", "LAK - Laotian Kip"))
        self.combobox_HAVE_currencies.setItemText(84, _translate("MainWindow", "LBP - Lebanese Pound"))
        self.combobox_HAVE_currencies.setItemText(85, _translate("MainWindow", "LKR - Sri Lankan Rupee"))
        self.combobox_HAVE_currencies.setItemText(86, _translate("MainWindow", "LRD - Liberian Dollar"))
        self.combobox_HAVE_currencies.setItemText(87, _translate("MainWindow", "LSL - Lesotho Loti"))
        self.combobox_HAVE_currencies.setItemText(88, _translate("MainWindow", "LTL - Lithuanian Litas"))
        self.combobox_HAVE_currencies.setItemText(89, _translate("MainWindow", "LVL - Latvian Lats"))
        self.combobox_HAVE_currencies.setItemText(90, _translate("MainWindow", "LYD - Libyan Dinar"))
        self.combobox_HAVE_currencies.setItemText(91, _translate("MainWindow", "MAD - Moroccan Dirham"))
        self.combobox_HAVE_currencies.setItemText(92, _translate("MainWindow", "MDL - Moldovan Leu"))
        self.combobox_HAVE_currencies.setItemText(93, _translate("MainWindow", "MGA - Malagasy Ariary"))
        self.combobox_HAVE_currencies.setItemText(94, _translate("MainWindow", "MKD - Macedonian Denar"))
        self.combobox_HAVE_currencies.setItemText(95, _translate("MainWindow", "MMK - Myanma Kyat"))
        self.combobox_HAVE_currencies.setItemText(96, _translate("MainWindow", "MNT - Mongolian Tugrik"))
        self.combobox_HAVE_currencies.setItemText(97, _translate("MainWindow", "MOP - Macanese Pataca"))
        self.combobox_HAVE_currencies.setItemText(98, _translate("MainWindow", "MRO - Mauritanian Ouguiya"))
        self.combobox_HAVE_currencies.setItemText(99, _translate("MainWindow", "MUR - Mauritian Rupee"))
        self.combobox_HAVE_currencies.setItemText(100, _translate("MainWindow", "MVR - Maldivian Rufiyaa"))
        self.combobox_HAVE_currencies.setItemText(101, _translate("MainWindow", "MWK - Malawian Kwacha"))
        self.combobox_HAVE_currencies.setItemText(102, _translate("MainWindow", "MXN - Mexican Peso"))
        self.combobox_HAVE_currencies.setItemText(103, _translate("MainWindow", "MYR - Malaysian Ringgit"))
        self.combobox_HAVE_currencies.setItemText(104, _translate("MainWindow", "MZN - Mozambican Metical"))
        self.combobox_HAVE_currencies.setItemText(105, _translate("MainWindow", "NAD - Namibian Dollar"))
        self.combobox_HAVE_currencies.setItemText(106, _translate("MainWindow", "NGN - Nigerian Naira"))
        self.combobox_HAVE_currencies.setItemText(107, _translate("MainWindow", "NIO - Nicaraguan Córdoba"))
        self.combobox_HAVE_currencies.setItemText(108, _translate("MainWindow", "NOK - Norwegian Krone"))
        self.combobox_HAVE_currencies.setItemText(109, _translate("MainWindow", "NPR - Nepalese Rupee"))
        self.combobox_HAVE_currencies.setItemText(110, _translate("MainWindow", "OMR - Omani Rial"))
        self.combobox_HAVE_currencies.setItemText(111, _translate("MainWindow", "PAB - Panamanian Balboa"))
        self.combobox_HAVE_currencies.setItemText(112, _translate("MainWindow", "PEN - Peruvian Nuevo Sol"))
        self.combobox_HAVE_currencies.setItemText(113, _translate("MainWindow", "PGK - Papua New Guinean Kina"))
        self.combobox_HAVE_currencies.setItemText(114, _translate("MainWindow", "PHP - Philippine Peso"))
        self.combobox_HAVE_currencies.setItemText(115, _translate("MainWindow", "PKR - Pakistani Rupee"))
        self.combobox_HAVE_currencies.setItemText(116, _translate("MainWindow", "PLN - Polish Zloty"))
        self.combobox_HAVE_currencies.setItemText(117, _translate("MainWindow", "PYG - Paraguayan Guarani"))
        self.combobox_HAVE_currencies.setItemText(118, _translate("MainWindow", "QAR - Qatari Rial"))
        self.combobox_HAVE_currencies.setItemText(119, _translate("MainWindow", "RON - Romanian Leu"))
        self.combobox_HAVE_currencies.setItemText(120, _translate("MainWindow", "RSD - Serbian Dinar"))
        self.combobox_HAVE_currencies.setItemText(121, _translate("MainWindow", "RUB - Russian Ruble"))
        self.combobox_HAVE_currencies.setItemText(122, _translate("MainWindow", "RWF - Rwandan Franc"))
        self.combobox_HAVE_currencies.setItemText(123, _translate("MainWindow", "SAR - Saudi Riyal"))
        self.combobox_HAVE_currencies.setItemText(124, _translate("MainWindow", "SBD - Solomon Islands Dollar"))
        self.combobox_HAVE_currencies.setItemText(125, _translate("MainWindow", "SCR - Seychellois Rupee"))
        self.combobox_HAVE_currencies.setItemText(126, _translate("MainWindow", "SDG - Sudanese Pound"))
        self.combobox_HAVE_currencies.setItemText(127, _translate("MainWindow", "SGD - Singapore Dollar"))
        self.combobox_HAVE_currencies.setItemText(128, _translate("MainWindow", "SHP - Saint Helena Pound"))
        self.combobox_HAVE_currencies.setItemText(129, _translate("MainWindow", "SLL - Sierra Leonean Leone"))
        self.combobox_HAVE_currencies.setItemText(130, _translate("MainWindow", "SOS - Somali Shilling"))
        self.combobox_HAVE_currencies.setItemText(131, _translate("MainWindow", "SRD - Surinamese Dollar"))
        self.combobox_HAVE_currencies.setItemText(132, _translate("MainWindow", "STD - São Tomé and Príncipe Dobra"))
        self.combobox_HAVE_currencies.setItemText(133, _translate("MainWindow", "SVC - Salvadoran Colón"))
        self.combobox_HAVE_currencies.setItemText(134, _translate("MainWindow", "SYP - Syrian Pound"))
        self.combobox_HAVE_currencies.setItemText(135, _translate("MainWindow", "SZL - Swazi Lilangeni"))
        self.combobox_HAVE_currencies.setItemText(136, _translate("MainWindow", "THB - Thai Baht"))
        self.combobox_HAVE_currencies.setItemText(137, _translate("MainWindow", "TJS - Tajikistani Somoni"))
        self.combobox_HAVE_currencies.setItemText(138, _translate("MainWindow", "TMT - Turkmenistani Manat"))
        self.combobox_HAVE_currencies.setItemText(139, _translate("MainWindow", "TND - Tunisian Dinar"))
        self.combobox_HAVE_currencies.setItemText(140, _translate("MainWindow", "TOP - Tongan Paʻanga"))
        self.combobox_HAVE_currencies.setItemText(141, _translate("MainWindow", "TRY - Turkish Lira"))
        self.combobox_HAVE_currencies.setItemText(142, _translate("MainWindow", "TTD - Trinidad and Tobago Dollar"))
        self.combobox_HAVE_currencies.setItemText(143, _translate("MainWindow", "TWD - New Taiwan Dollar"))
        self.combobox_HAVE_currencies.setItemText(144, _translate("MainWindow", "TZS - Tanzanian Shilling"))
        self.combobox_HAVE_currencies.setItemText(145, _translate("MainWindow", "UAH - Ukrainian Hryvnia"))
        self.combobox_HAVE_currencies.setItemText(146, _translate("MainWindow", "UGX - Ugandan Shilling"))
        self.combobox_HAVE_currencies.setItemText(147, _translate("MainWindow", "UYU - Uruguayan Peso"))
        self.combobox_HAVE_currencies.setItemText(148, _translate("MainWindow", "UZS - Uzbekistan Som"))
        self.combobox_HAVE_currencies.setItemText(149, _translate("MainWindow", "VEF - Venezuelan Bolívar Fuerte"))
        self.combobox_HAVE_currencies.setItemText(150, _translate("MainWindow", "VND - Vietnamese Dong"))
        self.combobox_HAVE_currencies.setItemText(151, _translate("MainWindow", "VUV - Vanuatu Vatu"))
        self.combobox_HAVE_currencies.setItemText(152, _translate("MainWindow", "WST - Samoan Tala"))
        self.combobox_HAVE_currencies.setItemText(153, _translate("MainWindow", "XAF - CFA Franc BEAC"))
        self.combobox_HAVE_currencies.setItemText(154, _translate("MainWindow", "XCD - East Caribbean Dollar"))
        self.combobox_HAVE_currencies.setItemText(155, _translate("MainWindow", "XOF - CFA Franc BCEAO"))
        self.combobox_HAVE_currencies.setItemText(156, _translate("MainWindow", "XPF - CFP Franc"))
        self.combobox_HAVE_currencies.setItemText(157, _translate("MainWindow", "YER - Yemeni Rial"))
        self.combobox_HAVE_currencies.setItemText(158, _translate("MainWindow", "ZAR - South African Rand"))
        self.combobox_HAVE_currencies.setItemText(159, _translate("MainWindow", "ZMW - Zambian Kwacha"))
        self.combobox_HAVE_currencies.setItemText(160, _translate("MainWindow", "ZWL - Zimbabwean Dollar"))
        self.label_HAVE_title_crypto_currencies.setText(_translate("MainWindow", "Crypto Currencies"))
        self.combobox_HAVE_crypto_currencies.setItemText(0, _translate("MainWindow", "BTC - Bitcoin"))
        self.combobox_HAVE_crypto_currencies.setItemText(1, _translate("MainWindow", "ETH - Ethereum"))
        self.combobox_HAVE_crypto_currencies.setItemText(2, _translate("MainWindow", "ADA - Cardano"))
        self.combobox_HAVE_crypto_currencies.setItemText(3, _translate("MainWindow", "BNB - Binance Coin"))
        self.combobox_HAVE_crypto_currencies.setItemText(4, _translate("MainWindow", "USDT - TETHER"))
        self.combobox_HAVE_crypto_currencies.setItemText(5, _translate("MainWindow", "SOL - Solona"))
        self.combobox_HAVE_crypto_currencies.setItemText(6, _translate("MainWindow", "XRP - Xrp"))
        self.combobox_HAVE_crypto_currencies.setItemText(7, _translate("MainWindow", "DOGE - Dogecoin"))
        self.combobox_HAVE_crypto_currencies.setItemText(8, _translate("MainWindow", "DOT - Polkadot"))
        self.combobox_HAVE_crypto_currencies.setItemText(9, _translate("MainWindow", "USDC - USD Coin"))
        self.combobox_HAVE_crypto_currencies.setItemText(10, _translate("MainWindow", "LUNA - Terra"))
        self.combobox_HAVE_crypto_currencies.setItemText(11, _translate("MainWindow", "UNI - Uniswap"))
        self.combobox_HAVE_crypto_currencies.setItemText(12, _translate("MainWindow", "LINK - Chainlink"))
        self.combobox_HAVE_crypto_currencies.setItemText(13, _translate("MainWindow", "BUSD - Binance USD"))
        self.combobox_HAVE_crypto_currencies.setItemText(14, _translate("MainWindow", "BCH - Bitcoin Cash"))
        self.combobox_HAVE_crypto_currencies.setItemText(15, _translate("MainWindow", "LTC - Litecoin"))
        self.combobox_HAVE_crypto_currencies.setItemText(16, _translate("MainWindow", "ALGO - Algorand"))
        self.combobox_HAVE_crypto_currencies.setItemText(17, _translate("MainWindow", "AVAX - Avalanche"))
        self.combobox_HAVE_crypto_currencies.setItemText(18, _translate("MainWindow", "ICP - Internet Computer"))
        self.combobox_HAVE_crypto_currencies.setItemText(19, _translate("MainWindow", "WBTC - Wrapped Bitcoin"))
        self.combobox_HAVE_crypto_currencies.setItemText(20, _translate("MainWindow", "MATIC - Polygon"))
        self.combobox_HAVE_crypto_currencies.setItemText(21, _translate("MainWindow", "FTT - FTX Token"))
        self.combobox_HAVE_crypto_currencies.setItemText(22, _translate("MainWindow", "FIL - Filecoin"))
        self.combobox_HAVE_crypto_currencies.setItemText(23, _translate("MainWindow", "XLM - Stellar"))
        self.combobox_HAVE_crypto_currencies.setItemText(24, _translate("MainWindow", "VET - VeChain"))
        self.combobox_HAVE_crypto_currencies.setItemText(25, _translate("MainWindow", "ETC - Ethereum Classic"))
        self.combobox_HAVE_crypto_currencies.setItemText(26, _translate("MainWindow", "THETA - Theta"))
        self.combobox_HAVE_crypto_currencies.setItemText(27, _translate("MainWindow", "DAI - Dai"))
        self.combobox_HAVE_crypto_currencies.setItemText(28, _translate("MainWindow", "TRX - Tron"))
        self.combobox_HAVE_crypto_currencies.setItemText(29, _translate("MainWindow", "ATOM - Cosmos"))
        self.combobox_HAVE_crypto_currencies.setItemText(30, _translate("MainWindow", "XTZ - Tezos"))
        self.combobox_HAVE_crypto_currencies.setItemText(31, _translate("MainWindow", "XMR - Monero"))
        self.combobox_HAVE_crypto_currencies.setItemText(32, _translate("MainWindow", "MIOTA - IOTA"))
        self.combobox_HAVE_crypto_currencies.setItemText(33, _translate("MainWindow", "EOS - EOS"))
        self.combobox_HAVE_crypto_currencies.setItemText(34, _translate("MainWindow", "XEC - ECash"))
        self.combobox_HAVE_crypto_currencies.setItemText(35, _translate("MainWindow", "CRO - Crypto.com Coin"))
        self.combobox_HAVE_crypto_currencies.setItemText(36, _translate("MainWindow", "CAKE - PancakeSwap"))
        self.combobox_HAVE_crypto_currencies.setItemText(37, _translate("MainWindow", "EGLD - Elrond"))
        self.combobox_HAVE_crypto_currencies.setItemText(38, _translate("MainWindow", "AAVE - Aave"))
        self.combobox_HAVE_crypto_currencies.setItemText(39, _translate("MainWindow", "NEAR - NEAR Protocol"))
        self.combobox_HAVE_crypto_currencies.setItemText(40, _translate("MainWindow", "AXS - Axie Infinity"))
        self.combobox_HAVE_crypto_currencies.setItemText(41, _translate("MainWindow", "FTM - Fantom"))
        self.combobox_HAVE_crypto_currencies.setItemText(42, _translate("MainWindow", "GRT - The Graph"))
        self.combobox_HAVE_crypto_currencies.setItemText(43, _translate("MainWindow", "QNT - Quant"))
        self.combobox_HAVE_crypto_currencies.setItemText(44, _translate("MainWindow", "BTCB - Bitcoin BEP2"))
        self.combobox_HAVE_crypto_currencies.setItemText(45, _translate("MainWindow", "NEO - Neo"))
        self.combobox_HAVE_crypto_currencies.setItemText(46, _translate("MainWindow", "KLAY - Klaytn"))
        self.combobox_HAVE_crypto_currencies.setItemText(47, _translate("MainWindow", "KSM - Kusama"))
        self.combobox_HAVE_crypto_currencies.setItemText(48, _translate("MainWindow", "WAVES - Waves"))
        self.combobox_HAVE_crypto_currencies.setItemText(49, _translate("MainWindow", "HBAR - Hedera Hashgraph"))
        self.combobox_HAVE_crypto_currencies.setItemText(50, _translate("MainWindow", "BSV - Bitcoin SV"))
        self.combobox_HAVE_crypto_currencies.setItemText(51, _translate("MainWindow", "LEO - UNUS SED LEO"))
        self.combobox_HAVE_crypto_currencies.setItemText(52, _translate("MainWindow", "MKR - Maker"))
        self.combobox_HAVE_crypto_currencies.setItemText(53, _translate("MainWindow", "SHIB - SHIBA INU"))
        self.combobox_HAVE_crypto_currencies.setItemText(54, _translate("MainWindow", "BTT - BitTorrent"))
        self.combobox_HAVE_crypto_currencies.setItemText(55, _translate("MainWindow", "UST - TerraUSD"))
        self.combobox_HAVE_crypto_currencies.setItemText(56, _translate("MainWindow", "HT - Huobi Token"))
        self.combobox_HAVE_crypto_currencies.setItemText(57, _translate("MainWindow", "AMP - Amp"))
        self.combobox_HAVE_crypto_currencies.setItemText(58, _translate("MainWindow", "COMP - Compound"))
        self.combobox_HAVE_crypto_currencies.setItemText(59, _translate("MainWindow", "AR - Arweave"))
        self.combobox_HAVE_crypto_currencies.setItemText(60, _translate("MainWindow", "DASH - Dash"))
        self.combobox_HAVE_crypto_currencies.setItemText(61, _translate("MainWindow", "REV - Revain"))
        self.combobox_HAVE_crypto_currencies.setItemText(62, _translate("MainWindow", "CHZ - Chiliz"))
        self.combobox_HAVE_crypto_currencies.setItemText(63, _translate("MainWindow", "DCR - Decred"))
        self.combobox_HAVE_crypto_currencies.setItemText(64, _translate("MainWindow", "RUNE - THORChain"))
        self.combobox_HAVE_crypto_currencies.setItemText(65, _translate("MainWindow", "HNT - Helium"))
        self.combobox_HAVE_crypto_currencies.setItemText(66, _translate("MainWindow", "ONE - Harmony"))
        self.combobox_HAVE_crypto_currencies.setItemText(67, _translate("MainWindow", "STX - Stacks"))
        self.combobox_HAVE_crypto_currencies.setItemText(68, _translate("MainWindow", "HOT - Holo"))
        self.combobox_HAVE_crypto_currencies.setItemText(69, _translate("MainWindow", "ZEC - Zcash"))
        self.combobox_HAVE_crypto_currencies.setItemText(70, _translate("MainWindow", "TFUEL - Theta Fuel"))
        self.combobox_HAVE_crypto_currencies.setItemText(71, _translate("MainWindow", "XEM - NEM"))
        self.combobox_HAVE_crypto_currencies.setItemText(72, _translate("MainWindow", "CELO - Celo"))
        self.combobox_HAVE_crypto_currencies.setItemText(73, _translate("MainWindow", "XDC - XinFin"))
        self.combobox_HAVE_crypto_currencies.setItemText(74, _translate("MainWindow", "MANA - Decentraland"))
        self.combobox_HAVE_crypto_currencies.setItemText(75, _translate("MainWindow", "ENJ - Enjin Coin"))
        self.combobox_HAVE_crypto_currencies.setItemText(76, _translate("MainWindow", "TUSD - TrueUSD"))
        self.combobox_HAVE_crypto_currencies.setItemText(77, _translate("MainWindow", "IOST - IOST"))
        self.combobox_HAVE_crypto_currencies.setItemText(78, _translate("MainWindow", "CEL - Celsius"))
        self.combobox_HAVE_crypto_currencies.setItemText(79, _translate("MainWindow", "SUSHI - Sushiswap"))
        self.combobox_HAVE_crypto_currencies.setItemText(80, _translate("MainWindow", "ZIL - Zilliqa"))
        self.combobox_HAVE_crypto_currencies.setItemText(81, _translate("MainWindow", "QTUM - Qtum"))
        self.combobox_HAVE_crypto_currencies.setItemText(82, _translate("MainWindow", "SNX - Synthetix"))
        self.combobox_HAVE_crypto_currencies.setItemText(83, _translate("MainWindow", "ICX - ICON"))
        self.combobox_HAVE_crypto_currencies.setItemText(84, _translate("MainWindow", "YFI - Yearn.finance"))
        self.combobox_HAVE_crypto_currencies.setItemText(85, _translate("MainWindow", "MDX - Mdex"))
        self.combobox_HAVE_crypto_currencies.setItemText(86, _translate("MainWindow", "MINA - Mina"))
        self.combobox_HAVE_crypto_currencies.setItemText(87, _translate("MainWindow", "OMG - OMG Network"))
        self.combobox_HAVE_crypto_currencies.setItemText(88, _translate("MainWindow", "BTG - Bitcoin Gold"))
        self.combobox_HAVE_crypto_currencies.setItemText(89, _translate("MainWindow", "FLOW - Flow"))
        self.combobox_HAVE_crypto_currencies.setItemText(90, _translate("MainWindow", "BAT - Basic Attention Token"))
        self.combobox_HAVE_crypto_currencies.setItemText(91, _translate("MainWindow", "RVN - Ravencoin"))
        self.combobox_HAVE_crypto_currencies.setItemText(92, _translate("MainWindow", "OKB - OKB"))
        self.combobox_HAVE_crypto_currencies.setItemText(93, _translate("MainWindow", "TEL - Telcoin"))
        self.combobox_HAVE_crypto_currencies.setItemText(94, _translate("MainWindow", "AUDIO - Audius"))
        self.combobox_HAVE_crypto_currencies.setItemText(95, _translate("MainWindow", "PERP - Curve DAO Token"))
        self.combobox_HAVE_crypto_currencies.setItemText(96, _translate("MainWindow", "ZEN - Horizen"))
        self.combobox_HAVE_crypto_currencies.setItemText(97, _translate("MainWindow", "BNT - Bancor"))
        self.combobox_HAVE_crypto_currencies.setItemText(98, _translate("MainWindow", "SC - Siacoin"))
        self.lineedit_HAVE_input.setPlaceholderText(_translate("MainWindow", "0.00"))
        self.button_change.setText(_translate("MainWindow", "⇵"))
        self.button_convert.setText(_translate("MainWindow", "Convert"))
        self.groupbox_WANT.setTitle(_translate("MainWindow", "Currency I Want"))
        self.label_WANT_title_currencies.setText(_translate("MainWindow", "Currencies"))
        self.label_WANT_title_crypto_currencies.setText(_translate("MainWindow", "Crypto Currencies"))
        self.combobox_WANT_currencies.setItemText(0, _translate("MainWindow", "USD - US Dollar"))
        self.combobox_WANT_currencies.setItemText(1, _translate("MainWindow", "EUR - Euro"))
        self.combobox_WANT_currencies.setItemText(2, _translate("MainWindow", "JPY - Japanese Yen"))
        self.combobox_WANT_currencies.setItemText(3, _translate("MainWindow", "GBP - British Pound Sterling"))
        self.combobox_WANT_currencies.setItemText(4, _translate("MainWindow", "AUD - Australian Dollar"))
        self.combobox_WANT_currencies.setItemText(5, _translate("MainWindow", "CAD - Canadian Dollar"))
        self.combobox_WANT_currencies.setItemText(6, _translate("MainWindow", "CHF - Swiss Franc"))
        self.combobox_WANT_currencies.setItemText(7, _translate("MainWindow", "CNY - Chinese Yuan"))
        self.combobox_WANT_currencies.setItemText(8, _translate("MainWindow", "SEK - Swedish Krona"))
        self.combobox_WANT_currencies.setItemText(9, _translate("MainWindow", "NZD - New Zealand Dollar"))
        self.combobox_WANT_currencies.setItemText(10, _translate("MainWindow", "AED - Arab Emirates Dirham"))
        self.combobox_WANT_currencies.setItemText(11, _translate("MainWindow", "AFN - Afghan Afghani"))
        self.combobox_WANT_currencies.setItemText(12, _translate("MainWindow", "ALL - Albania Lek"))
        self.combobox_WANT_currencies.setItemText(13, _translate("MainWindow", "AMD - Armenian Dram"))
        self.combobox_WANT_currencies.setItemText(14, _translate("MainWindow", "ANG - Netherlands Antillean Guilder"))
        self.combobox_WANT_currencies.setItemText(15, _translate("MainWindow", "AOA - Angolan Kwanza"))
        self.combobox_WANT_currencies.setItemText(16, _translate("MainWindow", "ARS - Argentine Peso"))
        self.combobox_WANT_currencies.setItemText(17, _translate("MainWindow", "AWG - Aruban Florin"))
        self.combobox_WANT_currencies.setItemText(18, _translate("MainWindow", "AZN - Azerbaijani Manat"))
        self.combobox_WANT_currencies.setItemText(19,
                                                  _translate("MainWindow", "BAM - Bosnia-Herzegovina Convertible Mark"))
        self.combobox_WANT_currencies.setItemText(20, _translate("MainWindow", "BBD - Barbadian Dollar"))
        self.combobox_WANT_currencies.setItemText(21, _translate("MainWindow", "BDT - Bangladeshi Taka"))
        self.combobox_WANT_currencies.setItemText(22, _translate("MainWindow", "BGN - Bulgarian Lev"))
        self.combobox_WANT_currencies.setItemText(23, _translate("MainWindow", "BHD - Bahraini Dinar"))
        self.combobox_WANT_currencies.setItemText(24, _translate("MainWindow", "BIF - Burundian Franc"))
        self.combobox_WANT_currencies.setItemText(25, _translate("MainWindow", "BMD - Bermudan Dollar"))
        self.combobox_WANT_currencies.setItemText(26, _translate("MainWindow", "BND - Brunei Dollar"))
        self.combobox_WANT_currencies.setItemText(27, _translate("MainWindow", "BOB - Bolivian Boliviano"))
        self.combobox_WANT_currencies.setItemText(28, _translate("MainWindow", "BRL - Brazilian Real"))
        self.combobox_WANT_currencies.setItemText(29, _translate("MainWindow", "BSD - Bahamian Dollar"))
        self.combobox_WANT_currencies.setItemText(30, _translate("MainWindow", "BTN - Bhutanese Ngultrum"))
        self.combobox_WANT_currencies.setItemText(31, _translate("MainWindow", "BWP - Botswanan Pula"))
        self.combobox_WANT_currencies.setItemText(32, _translate("MainWindow", "BYR - Belarusian Ruble"))
        self.combobox_WANT_currencies.setItemText(33, _translate("MainWindow", "BZD - Belize Dollar"))
        self.combobox_WANT_currencies.setItemText(34, _translate("MainWindow", "CDF - Congolese Franc"))
        self.combobox_WANT_currencies.setItemText(35, _translate("MainWindow", "CLF - Chilean Unit of Account"))
        self.combobox_WANT_currencies.setItemText(36, _translate("MainWindow", "CLP - Chilean Peso"))
        self.combobox_WANT_currencies.setItemText(37, _translate("MainWindow", "COP - Colombian Peso"))
        self.combobox_WANT_currencies.setItemText(38, _translate("MainWindow", "CRC - Costa Rican Colón"))
        self.combobox_WANT_currencies.setItemText(39, _translate("MainWindow", "CUC - Cuban Convertible Peso"))
        self.combobox_WANT_currencies.setItemText(40, _translate("MainWindow", "CUP - Cuban Peso"))
        self.combobox_WANT_currencies.setItemText(41, _translate("MainWindow", "CVE - Cape Verdean Escudo"))
        self.combobox_WANT_currencies.setItemText(42, _translate("MainWindow", "CZK - Czech Republic Koruna"))
        self.combobox_WANT_currencies.setItemText(43, _translate("MainWindow", "DJF - Djiboutian Franc"))
        self.combobox_WANT_currencies.setItemText(44, _translate("MainWindow", "DKK - Danish Krone"))
        self.combobox_WANT_currencies.setItemText(45, _translate("MainWindow", "DOP - Dominican Peso"))
        self.combobox_WANT_currencies.setItemText(46, _translate("MainWindow", "DZD - Algerian Dinar"))
        self.combobox_WANT_currencies.setItemText(47, _translate("MainWindow", "EGP - Egyptian Pound"))
        self.combobox_WANT_currencies.setItemText(48, _translate("MainWindow", "ERN - Eritrean Nakfa"))
        self.combobox_WANT_currencies.setItemText(49, _translate("MainWindow", "ETB - Ethiopian Birr"))
        self.combobox_WANT_currencies.setItemText(50, _translate("MainWindow", "FJD - Fijian Dollar"))
        self.combobox_WANT_currencies.setItemText(51, _translate("MainWindow", "FKP - Falkland Islands Pound"))
        self.combobox_WANT_currencies.setItemText(52, _translate("MainWindow", "GEL - Georgian Lari"))
        self.combobox_WANT_currencies.setItemText(53, _translate("MainWindow", "GHS - Ghanaian Cedi"))
        self.combobox_WANT_currencies.setItemText(54, _translate("MainWindow", "GIP - Gibraltar Pound"))
        self.combobox_WANT_currencies.setItemText(55, _translate("MainWindow", "GMD - Gambian Dalasi"))
        self.combobox_WANT_currencies.setItemText(56, _translate("MainWindow", "GNF - Guinean Franc"))
        self.combobox_WANT_currencies.setItemText(57, _translate("MainWindow", "GTQ - Guatemalan Quetzal"))
        self.combobox_WANT_currencies.setItemText(58, _translate("MainWindow", "GYD - Guyanaese Dollar"))
        self.combobox_WANT_currencies.setItemText(59, _translate("MainWindow", "HKD - Hong Kong Dollar"))
        self.combobox_WANT_currencies.setItemText(60, _translate("MainWindow", "HNL - Honduran Lempira"))
        self.combobox_WANT_currencies.setItemText(61, _translate("MainWindow", "HRK - Croatian Kuna"))
        self.combobox_WANT_currencies.setItemText(62, _translate("MainWindow", "HTG - Haitian Gourde"))
        self.combobox_WANT_currencies.setItemText(63, _translate("MainWindow", "HUF - Hungarian Forint"))
        self.combobox_WANT_currencies.setItemText(64, _translate("MainWindow", "IDR - Indonesian Rupiah"))
        self.combobox_WANT_currencies.setItemText(65, _translate("MainWindow", "ILS - Israeli New Sheqel"))
        self.combobox_WANT_currencies.setItemText(66, _translate("MainWindow", "IMP - Manx pound"))
        self.combobox_WANT_currencies.setItemText(67, _translate("MainWindow", "INR - Indian Rupee"))
        self.combobox_WANT_currencies.setItemText(68, _translate("MainWindow", "IQD - Iraqi Dinar"))
        self.combobox_WANT_currencies.setItemText(69, _translate("MainWindow", "IRR - Iranian Rial"))
        self.combobox_WANT_currencies.setItemText(70, _translate("MainWindow", "ISK - Icelandic Króna"))
        self.combobox_WANT_currencies.setItemText(71, _translate("MainWindow", "JEP - Jersey Pound"))
        self.combobox_WANT_currencies.setItemText(72, _translate("MainWindow", "JMD - Jamaican Dollar"))
        self.combobox_WANT_currencies.setItemText(73, _translate("MainWindow", "JOD - Jordanian Dinar"))
        self.combobox_WANT_currencies.setItemText(74, _translate("MainWindow", "KES - Kenyan Shilling"))
        self.combobox_WANT_currencies.setItemText(75, _translate("MainWindow", "KGS - Kyrgystani Som"))
        self.combobox_WANT_currencies.setItemText(76, _translate("MainWindow", "KHR - Cambodian Riel"))
        self.combobox_WANT_currencies.setItemText(77, _translate("MainWindow", "KMF - Comorian Franc"))
        self.combobox_WANT_currencies.setItemText(78, _translate("MainWindow", "KPW - North Korean Won"))
        self.combobox_WANT_currencies.setItemText(79, _translate("MainWindow", "KRW - South Korean Won"))
        self.combobox_WANT_currencies.setItemText(80, _translate("MainWindow", "KWD - Kuwaiti Dinar"))
        self.combobox_WANT_currencies.setItemText(81, _translate("MainWindow", "KYD - Cayman Islands Dollar"))
        self.combobox_WANT_currencies.setItemText(82, _translate("MainWindow", "KZT - Kazakhstani Tenge"))
        self.combobox_WANT_currencies.setItemText(83, _translate("MainWindow", "LAK - Laotian Kip"))
        self.combobox_WANT_currencies.setItemText(84, _translate("MainWindow", "LBP - Lebanese Pound"))
        self.combobox_WANT_currencies.setItemText(85, _translate("MainWindow", "LKR - Sri Lankan Rupee"))
        self.combobox_WANT_currencies.setItemText(86, _translate("MainWindow", "LRD - Liberian Dollar"))
        self.combobox_WANT_currencies.setItemText(87, _translate("MainWindow", "LSL - Lesotho Loti"))
        self.combobox_WANT_currencies.setItemText(88, _translate("MainWindow", "LTL - Lithuanian Litas"))
        self.combobox_WANT_currencies.setItemText(89, _translate("MainWindow", "LVL - Latvian Lats"))
        self.combobox_WANT_currencies.setItemText(90, _translate("MainWindow", "LYD - Libyan Dinar"))
        self.combobox_WANT_currencies.setItemText(91, _translate("MainWindow", "MAD - Moroccan Dirham"))
        self.combobox_WANT_currencies.setItemText(92, _translate("MainWindow", "MDL - Moldovan Leu"))
        self.combobox_WANT_currencies.setItemText(93, _translate("MainWindow", "MGA - Malagasy Ariary"))
        self.combobox_WANT_currencies.setItemText(94, _translate("MainWindow", "MKD - Macedonian Denar"))
        self.combobox_WANT_currencies.setItemText(95, _translate("MainWindow", "MMK - Myanma Kyat"))
        self.combobox_WANT_currencies.setItemText(96, _translate("MainWindow", "MNT - Mongolian Tugrik"))
        self.combobox_WANT_currencies.setItemText(97, _translate("MainWindow", "MOP - Macanese Pataca"))
        self.combobox_WANT_currencies.setItemText(98, _translate("MainWindow", "MRO - Mauritanian Ouguiya"))
        self.combobox_WANT_currencies.setItemText(99, _translate("MainWindow", "MUR - Mauritian Rupee"))
        self.combobox_WANT_currencies.setItemText(100, _translate("MainWindow", "MVR - Maldivian Rufiyaa"))
        self.combobox_WANT_currencies.setItemText(101, _translate("MainWindow", "MWK - Malawian Kwacha"))
        self.combobox_WANT_currencies.setItemText(102, _translate("MainWindow", "MXN - Mexican Peso"))
        self.combobox_WANT_currencies.setItemText(103, _translate("MainWindow", "MYR - Malaysian Ringgit"))
        self.combobox_WANT_currencies.setItemText(104, _translate("MainWindow", "MZN - Mozambican Metical"))
        self.combobox_WANT_currencies.setItemText(105, _translate("MainWindow", "NAD - Namibian Dollar"))
        self.combobox_WANT_currencies.setItemText(106, _translate("MainWindow", "NGN - Nigerian Naira"))
        self.combobox_WANT_currencies.setItemText(107, _translate("MainWindow", "NIO - Nicaraguan Córdoba"))
        self.combobox_WANT_currencies.setItemText(108, _translate("MainWindow", "NOK - Norwegian Krone"))
        self.combobox_WANT_currencies.setItemText(109, _translate("MainWindow", "NPR - Nepalese Rupee"))
        self.combobox_WANT_currencies.setItemText(110, _translate("MainWindow", "OMR - Omani Rial"))
        self.combobox_WANT_currencies.setItemText(111, _translate("MainWindow", "PAB - Panamanian Balboa"))
        self.combobox_WANT_currencies.setItemText(112, _translate("MainWindow", "PEN - Peruvian Nuevo Sol"))
        self.combobox_WANT_currencies.setItemText(113, _translate("MainWindow", "PGK - Papua New Guinean Kina"))
        self.combobox_WANT_currencies.setItemText(114, _translate("MainWindow", "PHP - Philippine Peso"))
        self.combobox_WANT_currencies.setItemText(115, _translate("MainWindow", "PKR - Pakistani Rupee"))
        self.combobox_WANT_currencies.setItemText(116, _translate("MainWindow", "PLN - Polish Zloty"))
        self.combobox_WANT_currencies.setItemText(117, _translate("MainWindow", "PYG - Paraguayan Guarani"))
        self.combobox_WANT_currencies.setItemText(118, _translate("MainWindow", "QAR - Qatari Rial"))
        self.combobox_WANT_currencies.setItemText(119, _translate("MainWindow", "RON - Romanian Leu"))
        self.combobox_WANT_currencies.setItemText(120, _translate("MainWindow", "RSD - Serbian Dinar"))
        self.combobox_WANT_currencies.setItemText(121, _translate("MainWindow", "RUB - Russian Ruble"))
        self.combobox_WANT_currencies.setItemText(122, _translate("MainWindow", "RWF - Rwandan Franc"))
        self.combobox_WANT_currencies.setItemText(123, _translate("MainWindow", "SAR - Saudi Riyal"))
        self.combobox_WANT_currencies.setItemText(124, _translate("MainWindow", "SBD - Solomon Islands Dollar"))
        self.combobox_WANT_currencies.setItemText(125, _translate("MainWindow", "SCR - Seychellois Rupee"))
        self.combobox_WANT_currencies.setItemText(126, _translate("MainWindow", "SDG - Sudanese Pound"))
        self.combobox_WANT_currencies.setItemText(127, _translate("MainWindow", "SGD - Singapore Dollar"))
        self.combobox_WANT_currencies.setItemText(128, _translate("MainWindow", "SHP - Saint Helena Pound"))
        self.combobox_WANT_currencies.setItemText(129, _translate("MainWindow", "SLL - Sierra Leonean Leone"))
        self.combobox_WANT_currencies.setItemText(130, _translate("MainWindow", "SOS - Somali Shilling"))
        self.combobox_WANT_currencies.setItemText(131, _translate("MainWindow", "SRD - Surinamese Dollar"))
        self.combobox_WANT_currencies.setItemText(132, _translate("MainWindow", "STD - São Tomé and Príncipe Dobra"))
        self.combobox_WANT_currencies.setItemText(133, _translate("MainWindow", "SVC - Salvadoran Colón"))
        self.combobox_WANT_currencies.setItemText(134, _translate("MainWindow", "SYP - Syrian Pound"))
        self.combobox_WANT_currencies.setItemText(135, _translate("MainWindow", "SZL - Swazi Lilangeni"))
        self.combobox_WANT_currencies.setItemText(136, _translate("MainWindow", "THB - Thai Baht"))
        self.combobox_WANT_currencies.setItemText(137, _translate("MainWindow", "TJS - Tajikistani Somoni"))
        self.combobox_WANT_currencies.setItemText(138, _translate("MainWindow", "TMT - Turkmenistani Manat"))
        self.combobox_WANT_currencies.setItemText(139, _translate("MainWindow", "TND - Tunisian Dinar"))
        self.combobox_WANT_currencies.setItemText(140, _translate("MainWindow", "TOP - Tongan Paʻanga"))
        self.combobox_WANT_currencies.setItemText(141, _translate("MainWindow", "TRY - Turkish Lira"))
        self.combobox_WANT_currencies.setItemText(142, _translate("MainWindow", "TTD - Trinidad and Tobago Dollar"))
        self.combobox_WANT_currencies.setItemText(143, _translate("MainWindow", "TWD - New Taiwan Dollar"))
        self.combobox_WANT_currencies.setItemText(144, _translate("MainWindow", "TZS - Tanzanian Shilling"))
        self.combobox_WANT_currencies.setItemText(145, _translate("MainWindow", "UAH - Ukrainian Hryvnia"))
        self.combobox_WANT_currencies.setItemText(146, _translate("MainWindow", "UGX - Ugandan Shilling"))
        self.combobox_WANT_currencies.setItemText(147, _translate("MainWindow", "UYU - Uruguayan Peso"))
        self.combobox_WANT_currencies.setItemText(148, _translate("MainWindow", "UZS - Uzbekistan Som"))
        self.combobox_WANT_currencies.setItemText(149, _translate("MainWindow", "VEF - Venezuelan Bolívar Fuerte"))
        self.combobox_WANT_currencies.setItemText(150, _translate("MainWindow", "VND - Vietnamese Dong"))
        self.combobox_WANT_currencies.setItemText(151, _translate("MainWindow", "VUV - Vanuatu Vatu"))
        self.combobox_WANT_currencies.setItemText(152, _translate("MainWindow", "WST - Samoan Tala"))
        self.combobox_WANT_currencies.setItemText(153, _translate("MainWindow", "XAF - CFA Franc BEAC"))
        self.combobox_WANT_currencies.setItemText(154, _translate("MainWindow", "XCD - East Caribbean Dollar"))
        self.combobox_WANT_currencies.setItemText(155, _translate("MainWindow", "XOF - CFA Franc BCEAO"))
        self.combobox_WANT_currencies.setItemText(156, _translate("MainWindow", "XPF - CFP Franc"))
        self.combobox_WANT_currencies.setItemText(157, _translate("MainWindow", "YER - Yemeni Rial"))
        self.combobox_WANT_currencies.setItemText(158, _translate("MainWindow", "ZAR - South African Rand"))
        self.combobox_WANT_currencies.setItemText(159, _translate("MainWindow", "ZMW - Zambian Kwacha"))
        self.combobox_WANT_currencies.setItemText(160, _translate("MainWindow", "ZWL - Zimbabwean Dollar"))
        self.combobox_WANT_crypto_currencies.setItemText(0, _translate("MainWindow", "BTC - Bitcoin"))
        self.combobox_WANT_crypto_currencies.setItemText(1, _translate("MainWindow", "ETH - Ethereum"))
        self.combobox_WANT_crypto_currencies.setItemText(2, _translate("MainWindow", "ADA - Cardano"))
        self.combobox_WANT_crypto_currencies.setItemText(3, _translate("MainWindow", "BNB - Binance Coin"))
        self.combobox_WANT_crypto_currencies.setItemText(4, _translate("MainWindow", "USDT - TETHER"))
        self.combobox_WANT_crypto_currencies.setItemText(5, _translate("MainWindow", "SOL - Solona"))
        self.combobox_WANT_crypto_currencies.setItemText(6, _translate("MainWindow", "XRP - Xrp"))
        self.combobox_WANT_crypto_currencies.setItemText(7, _translate("MainWindow", "DOGE - Dogecoin"))
        self.combobox_WANT_crypto_currencies.setItemText(8, _translate("MainWindow", "DOT - Polkadot"))
        self.combobox_WANT_crypto_currencies.setItemText(9, _translate("MainWindow", "USDC - USD Coin"))
        self.combobox_WANT_crypto_currencies.setItemText(10, _translate("MainWindow", "LUNA - Terra"))
        self.combobox_WANT_crypto_currencies.setItemText(11, _translate("MainWindow", "UNI - Uniswap"))
        self.combobox_WANT_crypto_currencies.setItemText(12, _translate("MainWindow", "LINK - Chainlink"))
        self.combobox_WANT_crypto_currencies.setItemText(13, _translate("MainWindow", "BUSD - Binance USD"))
        self.combobox_WANT_crypto_currencies.setItemText(14, _translate("MainWindow", "BCH - Bitcoin Cash"))
        self.combobox_WANT_crypto_currencies.setItemText(15, _translate("MainWindow", "LTC - Litecoin"))
        self.combobox_WANT_crypto_currencies.setItemText(16, _translate("MainWindow", "ALGO - Algorand"))
        self.combobox_WANT_crypto_currencies.setItemText(17, _translate("MainWindow", "AVAX - Avalanche"))
        self.combobox_WANT_crypto_currencies.setItemText(18, _translate("MainWindow", "ICP - Internet Computer"))
        self.combobox_WANT_crypto_currencies.setItemText(19, _translate("MainWindow", "WBTC - Wrapped Bitcoin"))
        self.combobox_WANT_crypto_currencies.setItemText(20, _translate("MainWindow", "MATIC - Polygon"))
        self.combobox_WANT_crypto_currencies.setItemText(21, _translate("MainWindow", "FTT - FTX Token"))
        self.combobox_WANT_crypto_currencies.setItemText(22, _translate("MainWindow", "FIL - Filecoin"))
        self.combobox_WANT_crypto_currencies.setItemText(23, _translate("MainWindow", "XLM - Stellar"))
        self.combobox_WANT_crypto_currencies.setItemText(24, _translate("MainWindow", "VET - VeChain"))
        self.combobox_WANT_crypto_currencies.setItemText(25, _translate("MainWindow", "ETC - Ethereum Classic"))
        self.combobox_WANT_crypto_currencies.setItemText(26, _translate("MainWindow", "THETA - Theta"))
        self.combobox_WANT_crypto_currencies.setItemText(27, _translate("MainWindow", "DAI - Dai"))
        self.combobox_WANT_crypto_currencies.setItemText(28, _translate("MainWindow", "TRX - Tron"))
        self.combobox_WANT_crypto_currencies.setItemText(29, _translate("MainWindow", "ATOM - Cosmos"))
        self.combobox_WANT_crypto_currencies.setItemText(30, _translate("MainWindow", "XTZ - Tezos"))
        self.combobox_WANT_crypto_currencies.setItemText(31, _translate("MainWindow", "XMR - Monero"))
        self.combobox_WANT_crypto_currencies.setItemText(32, _translate("MainWindow", "MIOTA - IOTA"))
        self.combobox_WANT_crypto_currencies.setItemText(33, _translate("MainWindow", "EOS - EOS"))
        self.combobox_WANT_crypto_currencies.setItemText(34, _translate("MainWindow", "XEC - ECash"))
        self.combobox_WANT_crypto_currencies.setItemText(35, _translate("MainWindow", "CRO - Crypto.com Coin"))
        self.combobox_WANT_crypto_currencies.setItemText(36, _translate("MainWindow", "CAKE - PancakeSwap"))
        self.combobox_WANT_crypto_currencies.setItemText(37, _translate("MainWindow", "EGLD - Elrond"))
        self.combobox_WANT_crypto_currencies.setItemText(38, _translate("MainWindow", "AAVE - Aave"))
        self.combobox_WANT_crypto_currencies.setItemText(39, _translate("MainWindow", "NEAR - NEAR Protocol"))
        self.combobox_WANT_crypto_currencies.setItemText(40, _translate("MainWindow", "AXS - Axie Infinity"))
        self.combobox_WANT_crypto_currencies.setItemText(41, _translate("MainWindow", "FTM - Fantom"))
        self.combobox_WANT_crypto_currencies.setItemText(42, _translate("MainWindow", "GRT - The Graph"))
        self.combobox_WANT_crypto_currencies.setItemText(43, _translate("MainWindow", "QNT - Quant"))
        self.combobox_WANT_crypto_currencies.setItemText(44, _translate("MainWindow", "BTCB - Bitcoin BEP2"))
        self.combobox_WANT_crypto_currencies.setItemText(45, _translate("MainWindow", "NEO - Neo"))
        self.combobox_WANT_crypto_currencies.setItemText(46, _translate("MainWindow", "KLAY - Klaytn"))
        self.combobox_WANT_crypto_currencies.setItemText(47, _translate("MainWindow", "KSM - Kusama"))
        self.combobox_WANT_crypto_currencies.setItemText(48, _translate("MainWindow", "WAVES - Waves"))
        self.combobox_WANT_crypto_currencies.setItemText(49, _translate("MainWindow", "HBAR - Hedera Hashgraph"))
        self.combobox_WANT_crypto_currencies.setItemText(50, _translate("MainWindow", "BSV - Bitcoin SV"))
        self.combobox_WANT_crypto_currencies.setItemText(51, _translate("MainWindow", "LEO - UNUS SED LEO"))
        self.combobox_WANT_crypto_currencies.setItemText(52, _translate("MainWindow", "MKR - Maker"))
        self.combobox_WANT_crypto_currencies.setItemText(53, _translate("MainWindow", "SHIB - SHIBA INU"))
        self.combobox_WANT_crypto_currencies.setItemText(54, _translate("MainWindow", "BTT - BitTorrent"))
        self.combobox_WANT_crypto_currencies.setItemText(55, _translate("MainWindow", "UST - TerraUSD"))
        self.combobox_WANT_crypto_currencies.setItemText(56, _translate("MainWindow", "HT - Huobi Token"))
        self.combobox_WANT_crypto_currencies.setItemText(57, _translate("MainWindow", "AMP - Amp"))
        self.combobox_WANT_crypto_currencies.setItemText(58, _translate("MainWindow", "COMP - Compound"))
        self.combobox_WANT_crypto_currencies.setItemText(59, _translate("MainWindow", "AR - Arweave"))
        self.combobox_WANT_crypto_currencies.setItemText(60, _translate("MainWindow", "DASH - Dash"))
        self.combobox_WANT_crypto_currencies.setItemText(61, _translate("MainWindow", "REV - Revain"))
        self.combobox_WANT_crypto_currencies.setItemText(62, _translate("MainWindow", "CHZ - Chiliz"))
        self.combobox_WANT_crypto_currencies.setItemText(63, _translate("MainWindow", "DCR - Decred"))
        self.combobox_WANT_crypto_currencies.setItemText(64, _translate("MainWindow", "RUNE - THORChain"))
        self.combobox_WANT_crypto_currencies.setItemText(65, _translate("MainWindow", "HNT - Helium"))
        self.combobox_WANT_crypto_currencies.setItemText(66, _translate("MainWindow", "ONE - Harmony"))
        self.combobox_WANT_crypto_currencies.setItemText(67, _translate("MainWindow", "STX - Stacks"))
        self.combobox_WANT_crypto_currencies.setItemText(68, _translate("MainWindow", "HOT - Holo"))
        self.combobox_WANT_crypto_currencies.setItemText(69, _translate("MainWindow", "ZEC - Zcash"))
        self.combobox_WANT_crypto_currencies.setItemText(70, _translate("MainWindow", "TFUEL - Theta Fuel"))
        self.combobox_WANT_crypto_currencies.setItemText(71, _translate("MainWindow", "XEM - NEM"))
        self.combobox_WANT_crypto_currencies.setItemText(72, _translate("MainWindow", "CELO - Celo"))
        self.combobox_WANT_crypto_currencies.setItemText(73, _translate("MainWindow", "XDC - XinFin"))
        self.combobox_WANT_crypto_currencies.setItemText(74, _translate("MainWindow", "MANA - Decentraland"))
        self.combobox_WANT_crypto_currencies.setItemText(75, _translate("MainWindow", "ENJ - Enjin Coin"))
        self.combobox_WANT_crypto_currencies.setItemText(76, _translate("MainWindow", "TUSD - TrueUSD"))
        self.combobox_WANT_crypto_currencies.setItemText(77, _translate("MainWindow", "IOST - IOST"))
        self.combobox_WANT_crypto_currencies.setItemText(78, _translate("MainWindow", "CEL - Celsius"))
        self.combobox_WANT_crypto_currencies.setItemText(79, _translate("MainWindow", "SUSHI - Sushiswap"))
        self.combobox_WANT_crypto_currencies.setItemText(80, _translate("MainWindow", "ZIL - Zilliqa"))
        self.combobox_WANT_crypto_currencies.setItemText(81, _translate("MainWindow", "QTUM - Qtum"))
        self.combobox_WANT_crypto_currencies.setItemText(82, _translate("MainWindow", "SNX - Synthetix"))
        self.combobox_WANT_crypto_currencies.setItemText(83, _translate("MainWindow", "ICX - ICON"))
        self.combobox_WANT_crypto_currencies.setItemText(84, _translate("MainWindow", "YFI - Yearn.finance"))
        self.combobox_WANT_crypto_currencies.setItemText(85, _translate("MainWindow", "MDX - Mdex"))
        self.combobox_WANT_crypto_currencies.setItemText(86, _translate("MainWindow", "MINA - Mina"))
        self.combobox_WANT_crypto_currencies.setItemText(87, _translate("MainWindow", "OMG - OMG Network"))
        self.combobox_WANT_crypto_currencies.setItemText(88, _translate("MainWindow", "BTG - Bitcoin Gold"))
        self.combobox_WANT_crypto_currencies.setItemText(89, _translate("MainWindow", "FLOW - Flow"))
        self.combobox_WANT_crypto_currencies.setItemText(90, _translate("MainWindow", "BAT - Basic Attention Token"))
        self.combobox_WANT_crypto_currencies.setItemText(91, _translate("MainWindow", "RVN - Ravencoin"))
        self.combobox_WANT_crypto_currencies.setItemText(92, _translate("MainWindow", "OKB - OKB"))
        self.combobox_WANT_crypto_currencies.setItemText(93, _translate("MainWindow", "TEL - Telcoin"))
        self.combobox_WANT_crypto_currencies.setItemText(94, _translate("MainWindow", "AUDIO - Audius"))
        self.combobox_WANT_crypto_currencies.setItemText(95, _translate("MainWindow", "PERP - Curve DAO Token"))
        self.combobox_WANT_crypto_currencies.setItemText(96, _translate("MainWindow", "ZEN - Horizen"))
        self.combobox_WANT_crypto_currencies.setItemText(97, _translate("MainWindow", "BNT - Bancor"))
        self.combobox_WANT_crypto_currencies.setItemText(98, _translate("MainWindow", "SC - Siacoin"))
        self.lbl_copyright.setText(_translate("MainWindow",
                                              "<html><head/><body><p><span style=\" font-size:7pt; color:#000000;\">© Designed and Developed by </span><a href=\"https://github.com/mehmetguduk\"><span style=\" font-size:7pt; text-decoration: underline; color:#0000ff;\">Mehmet Güdük</span></a></p></body></html>"))


import images
